package com.cqq.leisure.dao;

import com.cqq.leisure.entity.HolidayPlan;
import com.cqq.leisure.entity.HolidayPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HolidayPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int countByExample(HolidayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int deleteByExample(HolidayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int deleteByPrimaryKey(Integer holidayPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int insert(HolidayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int insertSelective(HolidayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    List<HolidayPlan> selectByExample(HolidayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    HolidayPlan selectByPrimaryKey(Integer holidayPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") HolidayPlan record, @Param("example") HolidayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int updateByExample(@Param("record") HolidayPlan record, @Param("example") HolidayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int updateByPrimaryKeySelective(HolidayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int updateByPrimaryKey(HolidayPlan record);
}