package com.cqq.leisure.dao;

import com.cqq.leisure.entity.UserPlan;
import com.cqq.leisure.entity.UserPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int countByExample(UserPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int deleteByExample(UserPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int deleteByPrimaryKey(Integer userPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int insert(UserPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int insertSelective(UserPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    List<UserPlan> selectByExample(UserPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    UserPlan selectByPrimaryKey(Integer userPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserPlan record, @Param("example") UserPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int updateByExample(@Param("record") UserPlan record, @Param("example") UserPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int updateByPrimaryKeySelective(UserPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    int updateByPrimaryKey(UserPlan record);
}