package com.vieagr.distribution.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.github.pagehelper.StringUtil;
import com.vieagr.distribution.entity.base.BaseEntity;

public class BetOrderProduct extends BaseEntity {
    /**
     * 订单与商品关联id
     * 表字段 : bet_order_product.bet_order_product_id
     */
    private String betOrderProductId;

    /**
     * 订单主键id
     * 表字段 : bet_order_product.bet_order_product_order_id
     */
    private String betOrderProductOrderId;

    /**
     * 订单号
     * 表字段 : bet_order_product.bet_order_product_order_number
     */
    private String betOrderProductOrderNumber;

    /**
     * 商品主键id
     * 表字段 : bet_order_product.bet_order_product_product_id
     */
    private String betOrderProductProductId;

    /**
     * 商品名
     * 表字段 : bet_order_product.bet_order_product_product_name
     */
    private String betOrderProductProductName;

    /**
     * 商品数量
     * 表字段 : bet_order_product.bet_order_product_product_count
     */
    private String betOrderProductProductCount;

    /**
     * 订单与商品关联创建时间
     * 表字段 : bet_order_product.bet_order_product_create_time
     */
    private String betOrderProductCreateTime;

    /**
     * 订单与商品关联更新时间
     * 表字段 : bet_order_product.bet_order_product_update_time
     */
    private Date betOrderProductUpdateTime;

    /**
     * 商品原标价
     * 表字段 : bet_order_product.bet_order_product_product_former_price
     */
    private BigDecimal betOrderProductProductFormerPrice;

    /**
     * 商品时间成交价
     * 表字段 : bet_order_product.bet_order_product_product_sale_price
     */
    private BigDecimal betOrderProductProductSalePrice;

    /**
     * 本次订单商品的总价
     * 表字段 : bet_order_product.bet_order_product_product_total
     */
    private BigDecimal betOrderProductProductTotal;

    /**
     * 商品单价修改备注
     * 表字段 : bet_order_product.bet_order_product_univalent_remark
     */
    private String betOrderProductUnivalentRemark;

    /**
     * 订单与商品关联删除标记，1、未删除，2、已删除
     * 表字段 : bet_order_product.bet_order_product_del_flag
     */
    private Integer betOrderProductDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bet_order_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 商品单位名
     */
    private String betOrderProductProductUnitName;
    /**
     * 客户门店名称
     */
    private String sysCustomerStoreName;
    /**
     * 商品类型外键
     */
    private String betOrderProductProductTypeId;
    
    /**
     * 商品进价
     */
    private BigDecimal betOrderProductProductBidPrice;
    
    public BigDecimal getBetOrderProductProductBidPrice() {
		return betOrderProductProductBidPrice;
	}

	public void setBetOrderProductProductBidPrice(BigDecimal betOrderProductProductBidPrice) {
		this.betOrderProductProductBidPrice = betOrderProductProductBidPrice;
	}

	public String getBetOrderProductProductTypeId() {
		return betOrderProductProductTypeId;
	}

	public void setBetOrderProductProductTypeId(String betOrderProductProductTypeId) {
		this.betOrderProductProductTypeId = betOrderProductProductTypeId;
	}

	public String getSysCustomerStoreName() {
		return sysCustomerStoreName;
	}

	public void setSysCustomerStoreName(String sysCustomerStoreName) {
		this.sysCustomerStoreName = sysCustomerStoreName;
	}

	public String getBetOrderProductProductUnitName() {
		return betOrderProductProductUnitName;
	}

	public void setBetOrderProductProductUnitName(String betOrderProductProductUnitName) {
		this.betOrderProductProductUnitName = betOrderProductProductUnitName;
	}

	public String getBetOrderProductId() {
        return betOrderProductId;
    }

    public void setBetOrderProductId(String betOrderProductId) {
        this.betOrderProductId = betOrderProductId == null ? null : betOrderProductId.trim();
    }

    public String getBetOrderProductOrderId() {
        return betOrderProductOrderId;
    }

    public void setBetOrderProductOrderId(String betOrderProductOrderId) {
        this.betOrderProductOrderId = betOrderProductOrderId == null ? null : betOrderProductOrderId.trim();
    }

    public String getBetOrderProductOrderNumber() {
        return betOrderProductOrderNumber;
    }

    public void setBetOrderProductOrderNumber(String betOrderProductOrderNumber) {
        this.betOrderProductOrderNumber = betOrderProductOrderNumber == null ? null : betOrderProductOrderNumber.trim();
    }

    public String getBetOrderProductProductId() {
        return betOrderProductProductId;
    }

    public void setBetOrderProductProductId(String betOrderProductProductId) {
        this.betOrderProductProductId = betOrderProductProductId == null ? null : betOrderProductProductId.trim();
    }

    public String getBetOrderProductProductName() {
        return betOrderProductProductName;
    }

    public void setBetOrderProductProductName(String betOrderProductProductName) {
        this.betOrderProductProductName = betOrderProductProductName == null ? null : betOrderProductProductName.trim();
    }

    public String getBetOrderProductProductCount() {
        return betOrderProductProductCount;
    }

    public void setBetOrderProductProductCount(String betOrderProductProductCount) {
        this.betOrderProductProductCount = betOrderProductProductCount;
    }

    public String getBetOrderProductCreateTime() {
        return betOrderProductCreateTime;
    }

    public void setBetOrderProductCreateTime(String betOrderProductCreateTime) {
        this.betOrderProductCreateTime = betOrderProductCreateTime == null ? null : betOrderProductCreateTime.trim();
    }

    public Date getBetOrderProductUpdateTime() {
        return betOrderProductUpdateTime;
    }

    public void setBetOrderProductUpdateTime(Date betOrderProductUpdateTime) {
        this.betOrderProductUpdateTime = betOrderProductUpdateTime;
    }

    public BigDecimal getBetOrderProductProductFormerPrice() {
        return betOrderProductProductFormerPrice;
    }

    public void setBetOrderProductProductFormerPrice(BigDecimal betOrderProductProductFormerPrice) {
        this.betOrderProductProductFormerPrice = betOrderProductProductFormerPrice;
    }

    public BigDecimal getBetOrderProductProductSalePrice() {
        return betOrderProductProductSalePrice;
    }

    public void setBetOrderProductProductSalePrice(BigDecimal betOrderProductProductSalePrice) {
        this.betOrderProductProductSalePrice = betOrderProductProductSalePrice;
    }

    public BigDecimal getBetOrderProductProductTotal() {
        return betOrderProductProductTotal;
    }

    public void setBetOrderProductProductTotal(BigDecimal betOrderProductProductTotal) {
        this.betOrderProductProductTotal = betOrderProductProductTotal;
    }

    public String getBetOrderProductUnivalentRemark() {
        return StringUtil.isEmpty(betOrderProductUnivalentRemark) ? "" : betOrderProductUnivalentRemark;
    }

    public void setBetOrderProductUnivalentRemark(String betOrderProductUnivalentRemark) {
        this.betOrderProductUnivalentRemark = betOrderProductUnivalentRemark == null ? null : betOrderProductUnivalentRemark.trim();
    }

    public Integer getBetOrderProductDelFlag() {
        return betOrderProductDelFlag;
    }

    public void setBetOrderProductDelFlag(Integer betOrderProductDelFlag) {
        this.betOrderProductDelFlag = betOrderProductDelFlag;
    }

	@Override
	public String toString() {
		return "BetOrderProduct [betOrderProductId=" + betOrderProductId + ", betOrderProductOrderId="
				+ betOrderProductOrderId + ", betOrderProductOrderNumber=" + betOrderProductOrderNumber
				+ ", betOrderProductProductId=" + betOrderProductProductId + ", betOrderProductProductName="
				+ betOrderProductProductName + ", betOrderProductProductCount=" + betOrderProductProductCount
				+ ", betOrderProductCreateTime=" + betOrderProductCreateTime + ", betOrderProductUpdateTime="
				+ betOrderProductUpdateTime + ", betOrderProductProductFormerPrice=" + betOrderProductProductFormerPrice
				+ ", betOrderProductProductSalePrice=" + betOrderProductProductSalePrice
				+ ", betOrderProductProductTotal=" + betOrderProductProductTotal + ", betOrderProductUnivalentRemark="
				+ betOrderProductUnivalentRemark + ", betOrderProductDelFlag=" + betOrderProductDelFlag
				+ ", betOrderProductProductUnitName=" + betOrderProductProductUnitName + ", sysCustomerStoreName="
				+ sysCustomerStoreName + ", betOrderProductProductTypeId=" + betOrderProductProductTypeId
				+ ", betOrderProductProductBidPrice=" + betOrderProductProductBidPrice + "]";
	}
    
}