package com.vieagr.distribution.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

/**
 * 送货单
 * @author master
 *
 */
public class SerDelivery extends BaseEntity {
    /**
     * 送货单主键id
     * 表字段 : ser_delivery.ser_deliver_id
     */
    private String serDeliverId;

    /**
     * 送货时间
     * 表字段 : ser_delivery.ser_deliver_send_time
     */
    private String serDeliverSendTime;

    /**
     * 送货人id
     * 表字段 : ser_delivery.ser_deliver_send_id
     */
    private String serDeliverSendId;

    /**
     * 订单外键
     * 表字段 : ser_delivery.ser_deliver_order_id
     */
    private String serDeliverOrderId;

    /**
     * 送货单金额
     * 表字段 : ser_delivery.ser_deliver_amount
     */
    private BigDecimal serDeliverAmount;

    /**
     * 创建时间
     * 表字段 : ser_delivery.ser_deliver_create_time
     */
    private String serDeliverCreateTime;

    /**
     * 更新时间
     * 表字段 : ser_delivery.ser_deliver_update_time
     */
    private Date serDeliverUpdateTime;

    /**
     * 送货单反馈时间
     * 表字段 : ser_delivery.ser_deliver_back_time
     */
    private String serDeliverBackTime;

    /**
     * 送货单反馈状态，1、客户成功收货，2、客户拒绝收货
     * 表字段 : ser_delivery.ser_deliver_back_state
     */
    private Integer serDeliverBackState;

    /**
     * 送货单反馈具体详情
     * 表字段 : ser_delivery.ser_deliver_back_details
     */
    private String serDeliverBackDetails;

    /**
     * 送货单备注
     * 表字段 : ser_delivery.ser_deliver_remark
     */
    private String serDeliverRemark;

    /**
     * 送货单删除标记，1、未删除，2、已删除
     * 表字段 : ser_delivery.ser_deliver_del_flag
     */
    private Integer serDeliverDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ser_delivery
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getSerDeliverId() {
        return serDeliverId;
    }

    public void setSerDeliverId(String serDeliverId) {
        this.serDeliverId = serDeliverId == null ? null : serDeliverId.trim();
    }

    public String getSerDeliverSendTime() {
        return serDeliverSendTime;
    }

    public void setSerDeliverSendTime(String serDeliverSendTime) {
        this.serDeliverSendTime = serDeliverSendTime == null ? null : serDeliverSendTime.trim();
    }

    public String getSerDeliverSendId() {
        return serDeliverSendId;
    }

    public void setSerDeliverSendId(String serDeliverSendId) {
        this.serDeliverSendId = serDeliverSendId == null ? null : serDeliverSendId.trim();
    }

    public String getSerDeliverOrderId() {
        return serDeliverOrderId;
    }

    public void setSerDeliverOrderId(String serDeliverOrderId) {
        this.serDeliverOrderId = serDeliverOrderId == null ? null : serDeliverOrderId.trim();
    }

    public BigDecimal getSerDeliverAmount() {
        return serDeliverAmount;
    }

    public void setSerDeliverAmount(BigDecimal serDeliverAmount) {
        this.serDeliverAmount = serDeliverAmount;
    }

    public String getSerDeliverCreateTime() {
        return serDeliverCreateTime;
    }

    public void setSerDeliverCreateTime(String serDeliverCreateTime) {
        this.serDeliverCreateTime = serDeliverCreateTime == null ? null : serDeliverCreateTime.trim();
    }

    public Date getSerDeliverUpdateTime() {
        return serDeliverUpdateTime;
    }

    public void setSerDeliverUpdateTime(Date serDeliverUpdateTime) {
        this.serDeliverUpdateTime = serDeliverUpdateTime;
    }

    public String getSerDeliverBackTime() {
        return serDeliverBackTime;
    }

    public void setSerDeliverBackTime(String serDeliverBackTime) {
        this.serDeliverBackTime = serDeliverBackTime == null ? null : serDeliverBackTime.trim();
    }

    public Integer getSerDeliverBackState() {
        return serDeliverBackState;
    }

    public void setSerDeliverBackState(Integer serDeliverBackState) {
        this.serDeliverBackState = serDeliverBackState;
    }

    public String getSerDeliverBackDetails() {
        return serDeliverBackDetails;
    }

    public void setSerDeliverBackDetails(String serDeliverBackDetails) {
        this.serDeliverBackDetails = serDeliverBackDetails == null ? null : serDeliverBackDetails.trim();
    }

    public String getSerDeliverRemark() {
        return serDeliverRemark;
    }

    public void setSerDeliverRemark(String serDeliverRemark) {
        this.serDeliverRemark = serDeliverRemark == null ? null : serDeliverRemark.trim();
    }

    public Integer getSerDeliverDelFlag() {
        return serDeliverDelFlag;
    }

    public void setSerDeliverDelFlag(Integer serDeliverDelFlag) {
        this.serDeliverDelFlag = serDeliverDelFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serDeliverId=").append(serDeliverId);
        sb.append(", serDeliverSendTime=").append(serDeliverSendTime);
        sb.append(", serDeliverSendId=").append(serDeliverSendId);
        sb.append(", serDeliverOrderId=").append(serDeliverOrderId);
        sb.append(", serDeliverAmount=").append(serDeliverAmount);
        sb.append(", serDeliverCreateTime=").append(serDeliverCreateTime);
        sb.append(", serDeliverUpdateTime=").append(serDeliverUpdateTime);
        sb.append(", serDeliverBackTime=").append(serDeliverBackTime);
        sb.append(", serDeliverBackState=").append(serDeliverBackState);
        sb.append(", serDeliverBackDetails=").append(serDeliverBackDetails);
        sb.append(", serDeliverRemark=").append(serDeliverRemark);
        sb.append(", serDeliverDelFlag=").append(serDeliverDelFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}