package com.vieagr.distribution.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

public class SysCustomerGroupProduct extends BaseEntity {
    /**
     * 顾客分组商品模板id
     * 表字段 : sys_customer_group_product.sys_customer_group_product_id
     */
    private String sysCustomerGroupProductId;

    /**
     * 顾客分组模板商品分组id，同用户分组id，一对一对应
     * 表字段 : sys_customer_group_product.sys_customer_group_product_group_id
     */
    private String sysCustomerGroupProductGroupId;

    /**
     * 顾客分组商品模板商品id
     * 表字段 : sys_customer_group_product.sys_customer_group_product_product_id
     */
    private String sysCustomerGroupProductProductId;

    /**
     * 顾客分组商品模板商品员工餐卖价
     * 表字段 : sys_customer_group_product.sys_customer_group_product_product_staff_price
     */
    private BigDecimal sysCustomerGroupProductProductStaffPrice;

    /**
     * 顾客分组商品模板商品普通卖价
     * 表字段 : sys_customer_group_product.sys_customer_group_product_product_ordinary_price
     */
    private BigDecimal sysCustomerGroupProductProductOrdinaryPrice;

    /**
     * 顾客分组模板商品商品名
     * 表字段 : sys_customer_group_product.sys_customer_group_product_product_name
     */
    private String sysCustomerGroupProductProductName;

    /**
     * 顾客分组模板商品创建时间
     * 表字段 : sys_customer_group_product.sys_customer_group_product_create_time
     */
    private String sysCustomerGroupProductCreateTime;

    /**
     * 顾客分组模板商品修改时间
     * 表字段 : sys_customer_group_product.sys_customer_group_product_update_time
     */
    private Date sysCustomerGroupProductUpdateTime;

    /**
     * 顾客分组模板商品状态，1、启用，2禁用
     * 表字段 : sys_customer_group_product.sys_customer_group_product_state
     */
    private Integer sysCustomerGroupProductState;

    /**
     * 顾客分组模板商品删除标记，1、未删除，2、已删除'
     * 表字段 : sys_customer_group_product.sys_customer_group_product_del_flag
     */
    private Integer sysCustomerGroupProductDelFlag;

    /**
     * 顾客分组模板商品员工餐进价
     * 表字段 : sys_customer_group_product.sys_customer_group_product_staff_bid_price
     */
    private BigDecimal sysCustomerGroupProductStaffBidPrice;

    /**
     * 顾客分组模板商品普通进价
     * 表字段 : sys_customer_group_product.sys_customer_group_product_ordinary_bid_price
     */
    private BigDecimal sysCustomerGroupProductOrdinaryBidPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_customer_group_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 商品分类名称
     */
    private String sysProductTypeName;
    
    /**
     * 商品卖价
     */
    private BigDecimal sysProductPrice;
    
    public BigDecimal getSysProductPrice() {
		return sysProductPrice;
	}

	public void setSysProductPrice(BigDecimal sysProductPrice) {
		this.sysProductPrice = sysProductPrice;
	}

	public String getSysProductTypeName() {
		return sysProductTypeName;
	}

	public void setSysProductTypeName(String sysProductTypeName) {
		this.sysProductTypeName = sysProductTypeName;
	}

	public String getSysCustomerGroupProductId() {
        return sysCustomerGroupProductId;
    }

    public void setSysCustomerGroupProductId(String sysCustomerGroupProductId) {
        this.sysCustomerGroupProductId = sysCustomerGroupProductId == null ? null : sysCustomerGroupProductId.trim();
    }

    public String getSysCustomerGroupProductGroupId() {
        return sysCustomerGroupProductGroupId;
    }

    public void setSysCustomerGroupProductGroupId(String sysCustomerGroupProductGroupId) {
        this.sysCustomerGroupProductGroupId = sysCustomerGroupProductGroupId == null ? null : sysCustomerGroupProductGroupId.trim();
    }

    public String getSysCustomerGroupProductProductId() {
        return sysCustomerGroupProductProductId;
    }

    public void setSysCustomerGroupProductProductId(String sysCustomerGroupProductProductId) {
        this.sysCustomerGroupProductProductId = sysCustomerGroupProductProductId == null ? null : sysCustomerGroupProductProductId.trim();
    }

    public BigDecimal getSysCustomerGroupProductProductStaffPrice() {
        return sysCustomerGroupProductProductStaffPrice;
    }

    public void setSysCustomerGroupProductProductStaffPrice(BigDecimal sysCustomerGroupProductProductStaffPrice) {
        this.sysCustomerGroupProductProductStaffPrice = sysCustomerGroupProductProductStaffPrice;
    }

    public BigDecimal getSysCustomerGroupProductProductOrdinaryPrice() {
        return sysCustomerGroupProductProductOrdinaryPrice;
    }

    public void setSysCustomerGroupProductProductOrdinaryPrice(BigDecimal sysCustomerGroupProductProductOrdinaryPrice) {
        this.sysCustomerGroupProductProductOrdinaryPrice = sysCustomerGroupProductProductOrdinaryPrice;
    }

    public String getSysCustomerGroupProductProductName() {
        return sysCustomerGroupProductProductName;
    }

    public void setSysCustomerGroupProductProductName(String sysCustomerGroupProductProductName) {
        this.sysCustomerGroupProductProductName = sysCustomerGroupProductProductName == null ? null : sysCustomerGroupProductProductName.trim();
    }

    public String getSysCustomerGroupProductCreateTime() {
        return sysCustomerGroupProductCreateTime;
    }

    public void setSysCustomerGroupProductCreateTime(String sysCustomerGroupProductCreateTime) {
        this.sysCustomerGroupProductCreateTime = sysCustomerGroupProductCreateTime == null ? null : sysCustomerGroupProductCreateTime.trim();
    }

    public Date getSysCustomerGroupProductUpdateTime() {
        return sysCustomerGroupProductUpdateTime;
    }

    public void setSysCustomerGroupProductUpdateTime(Date sysCustomerGroupProductUpdateTime) {
        this.sysCustomerGroupProductUpdateTime = sysCustomerGroupProductUpdateTime;
    }

    public Integer getSysCustomerGroupProductState() {
        return sysCustomerGroupProductState;
    }

    public void setSysCustomerGroupProductState(Integer sysCustomerGroupProductState) {
        this.sysCustomerGroupProductState = sysCustomerGroupProductState;
    }

    public Integer getSysCustomerGroupProductDelFlag() {
        return sysCustomerGroupProductDelFlag;
    }

    public void setSysCustomerGroupProductDelFlag(Integer sysCustomerGroupProductDelFlag) {
        this.sysCustomerGroupProductDelFlag = sysCustomerGroupProductDelFlag;
    }

    public BigDecimal getSysCustomerGroupProductStaffBidPrice() {
        return sysCustomerGroupProductStaffBidPrice;
    }

    public void setSysCustomerGroupProductStaffBidPrice(BigDecimal sysCustomerGroupProductStaffBidPrice) {
        this.sysCustomerGroupProductStaffBidPrice = sysCustomerGroupProductStaffBidPrice;
    }

    public BigDecimal getSysCustomerGroupProductOrdinaryBidPrice() {
        return sysCustomerGroupProductOrdinaryBidPrice;
    }

    public void setSysCustomerGroupProductOrdinaryBidPrice(BigDecimal sysCustomerGroupProductOrdinaryBidPrice) {
        this.sysCustomerGroupProductOrdinaryBidPrice = sysCustomerGroupProductOrdinaryBidPrice;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysCustomerGroupProductId=").append(sysCustomerGroupProductId);
        sb.append(", sysCustomerGroupProductGroupId=").append(sysCustomerGroupProductGroupId);
        sb.append(", sysCustomerGroupProductProductId=").append(sysCustomerGroupProductProductId);
        sb.append(", sysCustomerGroupProductProductStaffPrice=").append(sysCustomerGroupProductProductStaffPrice);
        sb.append(", sysCustomerGroupProductProductOrdinaryPrice=").append(sysCustomerGroupProductProductOrdinaryPrice);
        sb.append(", sysCustomerGroupProductProductName=").append(sysCustomerGroupProductProductName);
        sb.append(", sysCustomerGroupProductCreateTime=").append(sysCustomerGroupProductCreateTime);
        sb.append(", sysCustomerGroupProductUpdateTime=").append(sysCustomerGroupProductUpdateTime);
        sb.append(", sysCustomerGroupProductState=").append(sysCustomerGroupProductState);
        sb.append(", sysCustomerGroupProductDelFlag=").append(sysCustomerGroupProductDelFlag);
        sb.append(", sysCustomerGroupProductStaffBidPrice=").append(sysCustomerGroupProductStaffBidPrice);
        sb.append(", sysCustomerGroupProductOrdinaryBidPrice=").append(sysCustomerGroupProductOrdinaryBidPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}