package com.vieagr.distribution.entity;

import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

public class SysProductType extends BaseEntity{
    /**
     * 商品类型主键
     * 表字段 : sys_product_type.sys_product_type_id
     */
    private String sysProductTypeId;

    /**
     * 商品类型名称
     * 表字段 : sys_product_type.sys_product_type_name
     */
    private String sysProductTypeName;

    /**
     * 商品类型创建时间
     * 表字段 : sys_product_type.sys_product_type_create_time
     */
    private String sysProductTypeCreateTime;

    /**
     * 商品类型更新时间
     * 表字段 : sys_product_type.sys_product_type_update_time
     */
    private Date sysProductTypeUpdateTime;

    /**
     * 商品类型删除标记，1、未删除，2、删除
     * 表字段 : sys_product_type.sys_product_type_del_flag
     */
    private Integer sysProductTypeDelFlag;

    /**
     * 商品类型状态，1、启用，2、禁用
     * 表字段 : sys_product_type.sys_product_type_state
     */
    private Integer sysProductTypeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_product_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getSysProductTypeId() {
        return sysProductTypeId;
    }

    public void setSysProductTypeId(String sysProductTypeId) {
        this.sysProductTypeId = sysProductTypeId == null ? null : sysProductTypeId.trim();
    }

    public String getSysProductTypeName() {
        return sysProductTypeName;
    }

    public void setSysProductTypeName(String sysProductTypeName) {
        this.sysProductTypeName = sysProductTypeName == null ? null : sysProductTypeName.trim();
    }

    public String getSysProductTypeCreateTime() {
        return sysProductTypeCreateTime;
    }

    public void setSysProductTypeCreateTime(String sysProductTypeCreateTime) {
        this.sysProductTypeCreateTime = sysProductTypeCreateTime == null ? null : sysProductTypeCreateTime.trim();
    }

    public Date getSysProductTypeUpdateTime() {
        return sysProductTypeUpdateTime;
    }

    public void setSysProductTypeUpdateTime(Date sysProductTypeUpdateTime) {
        this.sysProductTypeUpdateTime = sysProductTypeUpdateTime;
    }

    public Integer getSysProductTypeDelFlag() {
        return sysProductTypeDelFlag;
    }

    public void setSysProductTypeDelFlag(Integer sysProductTypeDelFlag) {
        this.sysProductTypeDelFlag = sysProductTypeDelFlag;
    }

    public Integer getSysProductTypeState() {
        return sysProductTypeState;
    }

    public void setSysProductTypeState(Integer sysProductTypeState) {
        this.sysProductTypeState = sysProductTypeState;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysProductTypeId=").append(sysProductTypeId);
        sb.append(", sysProductTypeName=").append(sysProductTypeName);
        sb.append(", sysProductTypeCreateTime=").append(sysProductTypeCreateTime);
        sb.append(", sysProductTypeUpdateTime=").append(sysProductTypeUpdateTime);
        sb.append(", sysProductTypeDelFlag=").append(sysProductTypeDelFlag);
        sb.append(", sysProductTypeState=").append(sysProductTypeState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}