package com.vieagr.distribution.entity;

import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

public class BetVehiclesCustomer extends BaseEntity {
    /**
     * 车辆与客户关联id
     * 表字段 : bet_vehicles_customer.bet_vehicles_customer_id
     */
    private String betVehiclesCustomerId;

    /**
     * 车辆id
     * 表字段 : bet_vehicles_customer.bet_vehicles_customer_vehicles_id
     */
    private String betVehiclesCustomerVehiclesId;

    /**
     * 客户id
     * 表字段 : bet_vehicles_customer.bet_vehicles_customer_customer_id
     */
    private String betVehiclesCustomerCustomerId;

    /**
     * 车辆与客户关联创建时间
     * 表字段 : bet_vehicles_customer.bet_vehicles_customer_create_time
     */
    private String betVehiclesCustomerCreateTime;

    /**
     * 车辆与客户关联更新时间
     * 表字段 : bet_vehicles_customer.bet_vehicles_customer_update_time
     */
    private Date betVehiclesCustomerUpdateTime;

    /**
     * 车辆与客户关联删除标记，1、未删除，2、已删除
     * 表字段 : bet_vehicles_customer.bet_vehicles_customer_del_flag
     */
    private Integer betVehiclesCustomerDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bet_vehicles_customer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getBetVehiclesCustomerId() {
        return betVehiclesCustomerId;
    }

    public void setBetVehiclesCustomerId(String betVehiclesCustomerId) {
        this.betVehiclesCustomerId = betVehiclesCustomerId == null ? null : betVehiclesCustomerId.trim();
    }

    public String getBetVehiclesCustomerVehiclesId() {
        return betVehiclesCustomerVehiclesId;
    }

    public void setBetVehiclesCustomerVehiclesId(String betVehiclesCustomerVehiclesId) {
        this.betVehiclesCustomerVehiclesId = betVehiclesCustomerVehiclesId == null ? null : betVehiclesCustomerVehiclesId.trim();
    }

    public String getBetVehiclesCustomerCustomerId() {
        return betVehiclesCustomerCustomerId;
    }

    public void setBetVehiclesCustomerCustomerId(String betVehiclesCustomerCustomerId) {
        this.betVehiclesCustomerCustomerId = betVehiclesCustomerCustomerId == null ? null : betVehiclesCustomerCustomerId.trim();
    }

    public String getBetVehiclesCustomerCreateTime() {
        return betVehiclesCustomerCreateTime;
    }

    public void setBetVehiclesCustomerCreateTime(String betVehiclesCustomerCreateTime) {
        this.betVehiclesCustomerCreateTime = betVehiclesCustomerCreateTime == null ? null : betVehiclesCustomerCreateTime.trim();
    }

    public Date getBetVehiclesCustomerUpdateTime() {
        return betVehiclesCustomerUpdateTime;
    }

    public void setBetVehiclesCustomerUpdateTime(Date betVehiclesCustomerUpdateTime) {
        this.betVehiclesCustomerUpdateTime = betVehiclesCustomerUpdateTime;
    }

    public Integer getBetVehiclesCustomerDelFlag() {
        return betVehiclesCustomerDelFlag;
    }

    public void setBetVehiclesCustomerDelFlag(Integer betVehiclesCustomerDelFlag) {
        this.betVehiclesCustomerDelFlag = betVehiclesCustomerDelFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", betVehiclesCustomerId=").append(betVehiclesCustomerId);
        sb.append(", betVehiclesCustomerVehiclesId=").append(betVehiclesCustomerVehiclesId);
        sb.append(", betVehiclesCustomerCustomerId=").append(betVehiclesCustomerCustomerId);
        sb.append(", betVehiclesCustomerCreateTime=").append(betVehiclesCustomerCreateTime);
        sb.append(", betVehiclesCustomerUpdateTime=").append(betVehiclesCustomerUpdateTime);
        sb.append(", betVehiclesCustomerDelFlag=").append(betVehiclesCustomerDelFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}