package com.vieagr.distribution.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.util.StringUtils;

import com.vieagr.distribution.base.config.Constant;
import com.vieagr.distribution.base.config.EnumConfig;
import com.vieagr.distribution.entity.base.BaseEntity;

/**
 * 客户订单
 * @author master
 *
 */
public class SerOrder extends BaseEntity {
    /**
     * 订单主键id
     * 表字段 : ser_order.ser_order_id
     */
    private String serOrderId;

    /**
     * 订单号
     * 表字段 : ser_order.ser_order_number
     */
    private String serOrderNumber;

    /**
     * 订单类型，1、普通订单，2、员工餐订单
     * 表字段 : ser_order.ser_order_type
     */
    private Integer serOrderType;

    /**
     * 订单状态，1、待备货，2、待配送，3、配送中，4、已配送完成，5、配送遇到问题
     * 表字段 : ser_order.ser_order_state
     */
    private Integer serOrderState;

    /**
     * 客户外键
     * 表字段 : ser_order.ser_order_customer_id
     */
    private String serOrderCustomerId;

    /**
     * 订单创建人id
     * 表字段 : ser_order.ser_order_creater_id
     */
    private String serOrderCreaterId;

    /**
     * 创建时间
     * 表字段 : ser_order.ser_order_create_time
     */
    private String serOrderCreateTime;

    /**
     * 更新时间
     * 表字段 : ser_order.ser_order_update_time
     */
    private Date serOrderUpdateTime;

    /**
     * 订单金额
     * 表字段 : ser_order.ser_order_amount
     */
    private BigDecimal serOrderAmount;

    /**
     * 订单商品总数
     * 表字段 : ser_order.ser_order_product_count
     */
    private Integer serOrderProductCount;

    /**
     * 订单反馈时间
     * 表字段 : ser_order.ser_order_back_time
     */
    private String serOrderBackTime;

    /**
     * 订单反馈状态，1、配送成功，2、配送失败，3、其他
     * 表字段 : ser_order.ser_order_back_state
     */
    private Integer serOrderBackState;

    /**
     * 订单备注
     * 表字段 : ser_order.ser_order_remark
     */
    private String serOrderRemark;

    /**
     * 订单反馈具体详情
     * 表字段 : ser_order.ser_order_back_details
     */
    private String serOrderBackDetails;

    /**
     * 订单修改次数
     * 表字段 : ser_order.ser_order_change_times
     */
    private Integer serOrderChangeTimes;

    /**
     * 订单删除标记，1、未删除，2已删除
     * 表字段 : ser_order.ser_order_del_flag
     */
    private Integer serOrderDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ser_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    
    /**
     * 商家门店名
     */
    private String sysCustomerStoreName;
    
    /**
     * 配送时间
     */
    private String serOrderSendTime;
    
    /**
     *	顾客名字
     */
    private String sysCustomerName;
    
    /**
     * 顾客门店地址
     */
    private String sysCustomerStoreAddress;

    /**
     * 送货车辆牌照
     */
    private String sysVehiclesPlateNumber;
    
    /**
     * 月份字符串时间
     */
    private String monthDate;
    
	public String getMonthDate() {
		return monthDate;
	}

	public void setMonthDate(String monthDate) {
		this.monthDate = monthDate;
	}

	public String getSysVehiclesPlateNumber() {
		
		return StringUtils.isEmpty(sysVehiclesPlateNumber) ? "" : sysVehiclesPlateNumber;
	}

	public void setSysVehiclesPlateNumber(String sysVehiclesPlateNumber) {
		this.sysVehiclesPlateNumber = sysVehiclesPlateNumber;
	}

	public String getSysCustomerStoreAddress() {
		return sysCustomerStoreAddress;
	}

	public void setSysCustomerStoreAddress(String sysCustomerStoreAddress) {
		this.sysCustomerStoreAddress = sysCustomerStoreAddress;
	}

	public String getSysCustomerName() {
		return sysCustomerName;
	}

	public void setSysCustomerName(String sysCustomerName) {
		this.sysCustomerName = sysCustomerName;
	}

	public String getSerOrderSendTime() {
		return serOrderSendTime;
	}

	public void setSerOrderSendTime(String serOrderSendTime) {
		this.serOrderSendTime = serOrderSendTime;
	}

	public String getSysCustomerStoreName() {
		return sysCustomerStoreName;
	}

	public void setSysCustomerStoreName(String sysCustomerStoreName) {
		this.sysCustomerStoreName = sysCustomerStoreName;
	}

	public String getSerOrderId() {
        return serOrderId;
    }

    public void setSerOrderId(String serOrderId) {
        this.serOrderId = serOrderId == null ? null : serOrderId.trim();
    }

    public String getSerOrderNumber() {
        return serOrderNumber;
    }

    public void setSerOrderNumber(String serOrderNumber) {
        this.serOrderNumber = serOrderNumber == null ? null : serOrderNumber.trim();
    }

    public Integer getSerOrderType() {
        return serOrderType;
    }

    public void setSerOrderType(Integer serOrderType) {
        this.serOrderType = serOrderType;
    }

    public Integer getSerOrderState() {
        return serOrderState;
    }

    public void setSerOrderState(Integer serOrderState) {
        this.serOrderState = serOrderState;
    }

    public String getSerOrderCustomerId() {
        return serOrderCustomerId;
    }

    public void setSerOrderCustomerId(String serOrderCustomerId) {
        this.serOrderCustomerId = serOrderCustomerId == null ? null : serOrderCustomerId.trim();
    }

    public String getSerOrderCreaterId() {
        return serOrderCreaterId;
    }

    public void setSerOrderCreaterId(String serOrderCreaterId) {
        this.serOrderCreaterId = serOrderCreaterId == null ? null : serOrderCreaterId.trim();
    }

    public String getSerOrderCreateTime() {
        return serOrderCreateTime;
    }

    public void setSerOrderCreateTime(String serOrderCreateTime) {
        this.serOrderCreateTime = serOrderCreateTime == null ? null : serOrderCreateTime.trim();
    }

    public Date getSerOrderUpdateTime() {
        return serOrderUpdateTime;
    }

    public void setSerOrderUpdateTime(Date serOrderUpdateTime) {
        this.serOrderUpdateTime = serOrderUpdateTime;
    }

    public BigDecimal getSerOrderAmount() {
        return serOrderAmount;
    }

    public void setSerOrderAmount(BigDecimal serOrderAmount) {
        this.serOrderAmount = serOrderAmount;
    }

    public Integer getSerOrderProductCount() {
        return serOrderProductCount;
    }

    public void setSerOrderProductCount(Integer serOrderProductCount) {
        this.serOrderProductCount = serOrderProductCount;
    }

    public String getSerOrderBackTime() {
        return serOrderBackTime;
    }

    public void setSerOrderBackTime(String serOrderBackTime) {
        this.serOrderBackTime = serOrderBackTime == null ? null : serOrderBackTime.trim();
    }

    public Integer getSerOrderBackState() {
        return serOrderBackState;
    }

    public void setSerOrderBackState(Integer serOrderBackState) {
        this.serOrderBackState = serOrderBackState;
    }

    public String getSerOrderRemark() {
        return serOrderRemark;
    }

    public void setSerOrderRemark(String serOrderRemark) {
        this.serOrderRemark = serOrderRemark == null ? null : serOrderRemark.trim();
    }

    public String getSerOrderBackDetails() {
        return serOrderBackDetails;
    }

    public void setSerOrderBackDetails(String serOrderBackDetails) {
        this.serOrderBackDetails = serOrderBackDetails == null ? null : serOrderBackDetails.trim();
    }

    public Integer getSerOrderChangeTimes() {
        return serOrderChangeTimes;
    }

    public void setSerOrderChangeTimes(Integer serOrderChangeTimes) {
        this.serOrderChangeTimes = serOrderChangeTimes;
    }

    public Integer getSerOrderDelFlag() {
        return serOrderDelFlag;
    }

    public void setSerOrderDelFlag(Integer serOrderDelFlag) {
        this.serOrderDelFlag = serOrderDelFlag;
    }
    
    public String getSerOrderTypeName(){
    	return this.serOrderType == null ? "" : EnumConfig.getName(this.serOrderType, Constant.SER_ORDER_TYPE);
    }
    
    public String getSerOrderStateName(){
    	return this.serOrderState == null ? "" : EnumConfig.getName(this.serOrderState, Constant.SER_ORDER_STATE);
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serOrderId=").append(serOrderId);
        sb.append(", serOrderNumber=").append(serOrderNumber);
        sb.append(", serOrderType=").append(serOrderType);
        sb.append(", serOrderState=").append(serOrderState);
        sb.append(", serOrderCustomerId=").append(serOrderCustomerId);
        sb.append(", serOrderCreaterId=").append(serOrderCreaterId);
        sb.append(", serOrderCreateTime=").append(serOrderCreateTime);
        sb.append(", serOrderUpdateTime=").append(serOrderUpdateTime);
        sb.append(", serOrderAmount=").append(serOrderAmount);
        sb.append(", serOrderProductCount=").append(serOrderProductCount);
        sb.append(", serOrderBackTime=").append(serOrderBackTime);
        sb.append(", serOrderBackState=").append(serOrderBackState);
        sb.append(", serOrderRemark=").append(serOrderRemark);
        sb.append(", serOrderBackDetails=").append(serOrderBackDetails);
        sb.append(", serOrderChangeTimes=").append(serOrderChangeTimes);
        sb.append(", serOrderDelFlag=").append(serOrderDelFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}