package com.vieagr.distribution.entity;

import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

public class SysCustomerGroup extends BaseEntity {
    /**
     * 顾客分组id
     * 表字段 : sys_customer_group.sys_customer_group_id
     */
    private String sysCustomerGroupId;

    /**
     * 顾客分组名称
     * 表字段 : sys_customer_group.sys_customer_group_name
     */
    private String sysCustomerGroupName;

    /**
     * 排序位
     * 表字段 : sys_customer_group.sys_customer_group_sort
     */
    private Integer sysCustomerGroupSort;

    /**
     * 顾客分组创建时间
     * 表字段 : sys_customer_group.sys_customer_group_create_time
     */
    private String sysCustomerGroupCreateTime;

    /**
     * 客户分组更新时间
     * 表字段 : sys_customer_group.sys_customer_group_update_time
     */
    private Date sysCustomerGroupUpdateTime;

    /**
     * 顾客分组状态，1、启用，2、禁用',
     * 表字段 : sys_customer_group.sys_customer_group_state
     */
    private Integer sysCustomerGroupState;

    /**
     * 顾客分组删除标记，1、未删除，2、已删除'
     * 表字段 : sys_customer_group.sys_customer_group_del_flag
     */
    private Integer sysCustomerGroupDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_customer_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 顾客名称
     */
    private String customerName;
    
    /**
     * 顾客数量
     */
    private Integer customerCount;
    
	public Integer getCustomerCount() {
		return customerCount;
	}

	public void setCustomerCount(Integer customerCount) {
		this.customerCount = customerCount;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getSysCustomerGroupId() {
        return sysCustomerGroupId;
    }

    public void setSysCustomerGroupId(String sysCustomerGroupId) {
        this.sysCustomerGroupId = sysCustomerGroupId == null ? null : sysCustomerGroupId.trim();
    }

    public String getSysCustomerGroupName() {
        return sysCustomerGroupName;
    }

    public void setSysCustomerGroupName(String sysCustomerGroupName) {
        this.sysCustomerGroupName = sysCustomerGroupName == null ? null : sysCustomerGroupName.trim();
    }

    public Integer getSysCustomerGroupSort() {
        return sysCustomerGroupSort;
    }

    public void setSysCustomerGroupSort(Integer sysCustomerGroupSort) {
        this.sysCustomerGroupSort = sysCustomerGroupSort;
    }

    public String getSysCustomerGroupCreateTime() {
        return sysCustomerGroupCreateTime;
    }

    public void setSysCustomerGroupCreateTime(String sysCustomerGroupCreateTime) {
        this.sysCustomerGroupCreateTime = sysCustomerGroupCreateTime == null ? null : sysCustomerGroupCreateTime.trim();
    }

    public Date getSysCustomerGroupUpdateTime() {
        return sysCustomerGroupUpdateTime;
    }

    public void setSysCustomerGroupUpdateTime(Date sysCustomerGroupUpdateTime) {
        this.sysCustomerGroupUpdateTime = sysCustomerGroupUpdateTime;
    }

    public Integer getSysCustomerGroupState() {
        return sysCustomerGroupState;
    }

    public void setSysCustomerGroupState(Integer sysCustomerGroupState) {
        this.sysCustomerGroupState = sysCustomerGroupState;
    }

    public Integer getSysCustomerGroupDelFlag() {
        return sysCustomerGroupDelFlag;
    }

    public void setSysCustomerGroupDelFlag(Integer sysCustomerGroupDelFlag) {
        this.sysCustomerGroupDelFlag = sysCustomerGroupDelFlag;
    }

	@Override
	public String toString() {
		return "SysCustomerGroup [sysCustomerGroupId=" + sysCustomerGroupId + ", sysCustomerGroupName="
				+ sysCustomerGroupName + ", sysCustomerGroupSort=" + sysCustomerGroupSort
				+ ", sysCustomerGroupCreateTime=" + sysCustomerGroupCreateTime + ", sysCustomerGroupUpdateTime="
				+ sysCustomerGroupUpdateTime + ", sysCustomerGroupState=" + sysCustomerGroupState
				+ ", sysCustomerGroupDelFlag=" + sysCustomerGroupDelFlag + ", customerName=" + customerName + "]";
	}
    
}