package com.vieagr.distribution.entity;

import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

/**
 * 系统文件
 * @author master
 *
 */
public class SysFile extends BaseEntity {
    /**
     * 系统文件主键
     * 表字段 : sys_file.sys_file_id
     */
    private String sysFileId;

    /**
     * 系统文件类型，1、图片，2、excel表格，3、word文档，4、其他
     * 表字段 : sys_file.sys_file_type
     */
    private Integer sysFileType;

    /**
     * 系统文件后缀名
     * 表字段 : sys_file.sys_file_postfix
     */
    private String sysFilePostfix;

    /**
     * 系统文件地址
     * 表字段 : sys_file.sys_file_url
     */
    private String sysFileUrl;

    /**
     * 系统文件创建人id
     * 表字段 : sys_file.sys_file_creater
     */
    private String sysFileCreater;

    /**
     * 系统文件创建时间
     * 表字段 : sys_file.sys_file_create_time
     */
    private String sysFileCreateTime;

    /**
     * 系统文件更新时间
     * 表字段 : sys_file.sys_file_update_time
     */
    private Date sysFileUpdateTime;

    /**
     * 系统文件备注
     * 表字段 : sys_file.sys_file_remark
     */
    private String sysFileRemark;

    /**
     * 系统文件删除标记，1、未删除，2、已删除
     * 表字段 : sys_file.sys_file_del_flag
     */
    private Integer sysFileDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    public SysFile(String sysFileId, Integer sysFileType, String sysFilePostfix){
    	this.sysFileId = sysFileId;
    	this.sysFileType = sysFileType;
    	this.sysFilePostfix =sysFilePostfix;
    }
    public String getSysFileId() {
        return sysFileId;
    }

    public void setSysFileId(String sysFileId) {
        this.sysFileId = sysFileId == null ? null : sysFileId.trim();
    }

    public Integer getSysFileType() {
        return sysFileType;
    }

    public void setSysFileType(Integer sysFileType) {
        this.sysFileType = sysFileType;
    }

    public String getSysFilePostfix() {
        return sysFilePostfix;
    }

    public void setSysFilePostfix(String sysFilePostfix) {
        this.sysFilePostfix = sysFilePostfix == null ? null : sysFilePostfix.trim();
    }

    public String getSysFileUrl() {
        return sysFileUrl;
    }

    public void setSysFileUrl(String sysFileUrl) {
        this.sysFileUrl = sysFileUrl == null ? null : sysFileUrl.trim();
    }

    public String getSysFileCreater() {
        return sysFileCreater;
    }

    public void setSysFileCreater(String sysFileCreater) {
        this.sysFileCreater = sysFileCreater == null ? null : sysFileCreater.trim();
    }

    public String getSysFileCreateTime() {
        return sysFileCreateTime;
    }

    public void setSysFileCreateTime(String sysFileCreateTime) {
        this.sysFileCreateTime = sysFileCreateTime == null ? null : sysFileCreateTime.trim();
    }

    public Date getSysFileUpdateTime() {
        return sysFileUpdateTime;
    }

    public void setSysFileUpdateTime(Date sysFileUpdateTime) {
        this.sysFileUpdateTime = sysFileUpdateTime;
    }

    public String getSysFileRemark() {
        return sysFileRemark;
    }

    public void setSysFileRemark(String sysFileRemark) {
        this.sysFileRemark = sysFileRemark == null ? null : sysFileRemark.trim();
    }

    public Integer getSysFileDelFlag() {
        return sysFileDelFlag;
    }

    public void setSysFileDelFlag(Integer sysFileDelFlag) {
        this.sysFileDelFlag = sysFileDelFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysFileId=").append(sysFileId);
        sb.append(", sysFileType=").append(sysFileType);
        sb.append(", sysFilePostfix=").append(sysFilePostfix);
        sb.append(", sysFileUrl=").append(sysFileUrl);
        sb.append(", sysFileCreater=").append(sysFileCreater);
        sb.append(", sysFileCreateTime=").append(sysFileCreateTime);
        sb.append(", sysFileUpdateTime=").append(sysFileUpdateTime);
        sb.append(", sysFileRemark=").append(sysFileRemark);
        sb.append(", sysFileDelFlag=").append(sysFileDelFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}