package com.vieagr.distribution.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysMensalBillCensus implements Serializable {
    /**
     * 月统计账单主键id
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_id
     */
    private String sysMensalBillCensusId;

    /**
     * 月统计账单订单类型，1、普通订单，2、员工餐订单
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_order_type
     */
    private Integer sysMensalBillCensusOrderType;

    /**
     * 月统计账单业务类型，1、总统计，2、客户统计
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_service_type
     */
    private Integer sysMensalBillCensusServiceType;

    /**
     * 月统计账单客户id
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_customer_id
     */
    private String sysMensalBillCensusCustomerId;

    /**
     * 月统计账单总售卖金额
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_sale_amount
     */
    private BigDecimal sysMensalBillCensusSaleAmount;

    /**
     * 月统计账单进价总金额
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_bid_amount
     */
    private BigDecimal sysMensalBillCensusBidAmount;

    /**
     * 月统计账单总利润金额
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_profit_amount
     */
    private BigDecimal sysMensalBillCensusProfitAmount;

    /**
     * 月统计账单订单总数
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_order_count
     */
    private Integer sysMensalBillCensusOrderCount;

    /**
     * 月统计账单统计月份，此处用字符串的年月
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_date
     */
    private String sysMensalBillCensusDate;

    /**
     * 月统计账单创建时间
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_create_time
     */
    private String sysMensalBillCensusCreateTime;

    /**
     * 月统计账单修改时间
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_update_time
     */
    private Date sysMensalBillCensusUpdateTime;

    /**
     * 月统计账单状态，1、有效，2、无效
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_state
     */
    private Integer sysMensalBillCensusState;

    /**
     * 月统计账单删除标记，1、未删除，2、已删除
     * 表字段 : sys_mensal_bill_census.sys_mensal_bill_census_del_flag
     */
    private Integer sysMensalBillCensusDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_mensal_bill_census
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getSysMensalBillCensusId() {
        return sysMensalBillCensusId;
    }

    public void setSysMensalBillCensusId(String sysMensalBillCensusId) {
        this.sysMensalBillCensusId = sysMensalBillCensusId == null ? null : sysMensalBillCensusId.trim();
    }

    public Integer getSysMensalBillCensusOrderType() {
        return sysMensalBillCensusOrderType;
    }

    public void setSysMensalBillCensusOrderType(Integer sysMensalBillCensusOrderType) {
        this.sysMensalBillCensusOrderType = sysMensalBillCensusOrderType;
    }

    public Integer getSysMensalBillCensusServiceType() {
        return sysMensalBillCensusServiceType;
    }

    public void setSysMensalBillCensusServiceType(Integer sysMensalBillCensusServiceType) {
        this.sysMensalBillCensusServiceType = sysMensalBillCensusServiceType;
    }

    public String getSysMensalBillCensusCustomerId() {
        return sysMensalBillCensusCustomerId;
    }

    public void setSysMensalBillCensusCustomerId(String sysMensalBillCensusCustomerId) {
        this.sysMensalBillCensusCustomerId = sysMensalBillCensusCustomerId == null ? null : sysMensalBillCensusCustomerId.trim();
    }

    public BigDecimal getSysMensalBillCensusSaleAmount() {
        return sysMensalBillCensusSaleAmount;
    }

    public void setSysMensalBillCensusSaleAmount(BigDecimal sysMensalBillCensusSaleAmount) {
        this.sysMensalBillCensusSaleAmount = sysMensalBillCensusSaleAmount;
    }

    public BigDecimal getSysMensalBillCensusBidAmount() {
        return sysMensalBillCensusBidAmount;
    }

    public void setSysMensalBillCensusBidAmount(BigDecimal sysMensalBillCensusBidAmount) {
        this.sysMensalBillCensusBidAmount = sysMensalBillCensusBidAmount;
    }

    public BigDecimal getSysMensalBillCensusProfitAmount() {
        return sysMensalBillCensusProfitAmount;
    }

    public void setSysMensalBillCensusProfitAmount(BigDecimal sysMensalBillCensusProfitAmount) {
        this.sysMensalBillCensusProfitAmount = sysMensalBillCensusProfitAmount;
    }

    public Integer getSysMensalBillCensusOrderCount() {
        return sysMensalBillCensusOrderCount;
    }

    public void setSysMensalBillCensusOrderCount(Integer sysMensalBillCensusOrderCount) {
        this.sysMensalBillCensusOrderCount = sysMensalBillCensusOrderCount;
    }

    public String getSysMensalBillCensusDate() {
        return sysMensalBillCensusDate;
    }

    public void setSysMensalBillCensusDate(String sysMensalBillCensusDate) {
        this.sysMensalBillCensusDate = sysMensalBillCensusDate == null ? null : sysMensalBillCensusDate.trim();
    }

    public String getSysMensalBillCensusCreateTime() {
        return sysMensalBillCensusCreateTime;
    }

    public void setSysMensalBillCensusCreateTime(String sysMensalBillCensusCreateTime) {
        this.sysMensalBillCensusCreateTime = sysMensalBillCensusCreateTime == null ? null : sysMensalBillCensusCreateTime.trim();
    }

    public Date getSysMensalBillCensusUpdateTime() {
        return sysMensalBillCensusUpdateTime;
    }

    public void setSysMensalBillCensusUpdateTime(Date sysMensalBillCensusUpdateTime) {
        this.sysMensalBillCensusUpdateTime = sysMensalBillCensusUpdateTime;
    }

    public Integer getSysMensalBillCensusState() {
        return sysMensalBillCensusState;
    }

    public void setSysMensalBillCensusState(Integer sysMensalBillCensusState) {
        this.sysMensalBillCensusState = sysMensalBillCensusState;
    }

    public Integer getSysMensalBillCensusDelFlag() {
        return sysMensalBillCensusDelFlag;
    }

    public void setSysMensalBillCensusDelFlag(Integer sysMensalBillCensusDelFlag) {
        this.sysMensalBillCensusDelFlag = sysMensalBillCensusDelFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysMensalBillCensusId=").append(sysMensalBillCensusId);
        sb.append(", sysMensalBillCensusOrderType=").append(sysMensalBillCensusOrderType);
        sb.append(", sysMensalBillCensusServiceType=").append(sysMensalBillCensusServiceType);
        sb.append(", sysMensalBillCensusCustomerId=").append(sysMensalBillCensusCustomerId);
        sb.append(", sysMensalBillCensusSaleAmount=").append(sysMensalBillCensusSaleAmount);
        sb.append(", sysMensalBillCensusBidAmount=").append(sysMensalBillCensusBidAmount);
        sb.append(", sysMensalBillCensusProfitAmount=").append(sysMensalBillCensusProfitAmount);
        sb.append(", sysMensalBillCensusOrderCount=").append(sysMensalBillCensusOrderCount);
        sb.append(", sysMensalBillCensusDate=").append(sysMensalBillCensusDate);
        sb.append(", sysMensalBillCensusCreateTime=").append(sysMensalBillCensusCreateTime);
        sb.append(", sysMensalBillCensusUpdateTime=").append(sysMensalBillCensusUpdateTime);
        sb.append(", sysMensalBillCensusState=").append(sysMensalBillCensusState);
        sb.append(", sysMensalBillCensusDelFlag=").append(sysMensalBillCensusDelFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}