package com.vieagr.distribution.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

/**
 * 商品
 * @author master
 *
 */
public class SysProduct extends BaseEntity {
    /**
     * 商品主键id
     * 表字段 : sys_product.sys_product_id
     */
    private String sysProductId;

    /**
     * 商品名称
     * 表字段 : sys_product.sys_product_name
     */
    private String sysProductName;

    /**
     * 商品拼音码
     * 表字段 : sys_product.sys_product_py_code
     */
    private String sysProductPyCode;

    /**
     * 商品拼音全称
     * 表字段 : sys_product.sys_product_py_name
     */
    private String sysProductPyName;

    /**
     * 商品状态，1、启用，2、禁用
     * 表字段 : sys_product.sys_product_state
     */
    private Integer sysProductState;

    /**
     * 商品计量单位
     * 表字段 : sys_product.sys_product_unit_name
     */
    private String sysProductUnitName;

    /**
     * 商品单价
     * 表字段 : sys_product.sys_product_price
     */
    private BigDecimal sysProductPrice;

    /**
     * 商品图片地址
     * 表字段 : sys_product.sys_product_img_url
     */
    private String sysProductImgUrl;

    /**
     * 商品创建时间
     * 表字段 : sys_product.sys_product_create_time
     */
    private String sysProductCreateTime;

    /**
     * 
     * 表字段 : sys_product.sys_product_update_time
     */
    private Date sysProductUpdateTime;

    /**
     * 商品被选中的时间
     * 表字段 : sys_product.sys_prodcut_choose_time
     */
    private String sysProdcutChooseTime;

    /**
     * 商品删除标记，1、未删除，2、已删除
     * 表字段 : sys_product.sys_product_del_flag
     */
    private Integer sysProductDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    
    /**
     *	添加订单时的商品数量
     */
    private String sysProductCount;

    /**
     * 添加订单时的商品成交价
     */
    private BigDecimal sysProductSalePrice;
    /**
     * 订单号
     */
    private String sysProductOrderNumber;
    /**
     * 商品类型外键
     */
    private String sysProductProductTypeId;
    
    /**
     * 商品类型名
     */
    private String sysProductTypeName;
    
    /**
     * 商品备注
     */
    private String betOrderProductUnivalentRemark;
    
    /**
     * 商品员工餐进价
     */
    private BigDecimal sysProductStaffBidPrice;
    
    /**
     * 商品进价普通
     */
    private BigDecimal sysProductOrdinaryBidPrice;
    
    /**
     * 商品普通卖价
     */
    private BigDecimal sysProductOrdinarySalePrice;
    
    /**
     * 商品员工餐卖价
     */
    private BigDecimal sysProductStaffSelfPrice;
    
	public BigDecimal getSysProductOrdinarySalePrice() {
		return sysProductOrdinarySalePrice;
	}

	public void setSysProductOrdinarySalePrice(BigDecimal sysProductOrdinarySalePrice) {
		this.sysProductOrdinarySalePrice = sysProductOrdinarySalePrice;
	}

	public BigDecimal getSysProductStaffSelfPrice() {
		return sysProductStaffSelfPrice;
	}

	public void setSysProductStaffSelfPrice(BigDecimal sysProductStaffSelfPrice) {
		this.sysProductStaffSelfPrice = sysProductStaffSelfPrice;
	}

	public BigDecimal getSysProductStaffBidPrice() {
		return sysProductStaffBidPrice;
	}

	public void setSysProductStaffBidPrice(BigDecimal sysProductStaffBidPrice) {
		this.sysProductStaffBidPrice = sysProductStaffBidPrice;
	}

	public BigDecimal getSysProductOrdinaryBidPrice() {
		return sysProductOrdinaryBidPrice;
	}

	public void setSysProductOrdinaryBidPrice(BigDecimal sysProductOrdinaryBidPrice) {
		this.sysProductOrdinaryBidPrice = sysProductOrdinaryBidPrice;
	}

	public String getBetOrderProductUnivalentRemark() {
		return betOrderProductUnivalentRemark;
	}

	public void setBetOrderProductUnivalentRemark(String betOrderProductUnivalentRemark) {
		this.betOrderProductUnivalentRemark = betOrderProductUnivalentRemark;
	}

	public String getSysProductTypeName() {
		return sysProductTypeName;
	}

	public void setSysProductTypeName(String sysProductTypeName) {
		this.sysProductTypeName = sysProductTypeName;
	}

	public String getSysProductProductTypeId() {
		return sysProductProductTypeId;
	}

	public void setSysProductProductTypeId(String sysProductProductTypeId) {
		this.sysProductProductTypeId = sysProductProductTypeId;
	}

	public String getSysProductOrderNumber() {
		return sysProductOrderNumber;
	}

	public void setSysProductOrderNumber(String sysProductOrderNumber) {
		this.sysProductOrderNumber = sysProductOrderNumber;
	}

	public BigDecimal getSysProductSalePrice() {
		return sysProductSalePrice;
	}

	public void setSysProductSalePrice(BigDecimal sysProductSalePrice) {
		this.sysProductSalePrice = sysProductSalePrice;
	}

	public String getSysProductCount() {
		return sysProductCount;
	}

	public void setSysProductCount(String sysProductCount) {
		this.sysProductCount = sysProductCount;
	}

	public String getSysProductId() {
        return sysProductId;
    }

    public void setSysProductId(String sysProductId) {
        this.sysProductId = sysProductId == null ? null : sysProductId.trim();
    }

    public String getSysProductName() {
        return sysProductName;
    }

    public void setSysProductName(String sysProductName) {
        this.sysProductName = sysProductName == null ? null : sysProductName.trim();
    }

    public String getSysProductPyCode() {
        return sysProductPyCode;
    }

    public void setSysProductPyCode(String sysProductPyCode) {
        this.sysProductPyCode = sysProductPyCode == null ? null : sysProductPyCode.trim();
    }

    public String getSysProductPyName() {
        return sysProductPyName;
    }

    public void setSysProductPyName(String sysProductPyName) {
        this.sysProductPyName = sysProductPyName == null ? null : sysProductPyName.trim();
    }

    public Integer getSysProductState() {
        return sysProductState;
    }

    public void setSysProductState(Integer sysProductState) {
        this.sysProductState = sysProductState;
    }

    public String getSysProductUnitName() {
        return sysProductUnitName;
    }

    public void setSysProductUnitName(String sysProductUnitName) {
        this.sysProductUnitName = sysProductUnitName == null ? null : sysProductUnitName.trim();
    }

    public BigDecimal getSysProductPrice() {
		return sysProductPrice;
	}

	public void setSysProductPrice(BigDecimal sysProductPrice) {
		this.sysProductPrice = sysProductPrice;
	}

	public String getSysProductImgUrl() {
        return sysProductImgUrl;
    }

    public void setSysProductImgUrl(String sysProductImgUrl) {
        this.sysProductImgUrl = sysProductImgUrl == null ? null : sysProductImgUrl.trim();
    }

    public String getSysProductCreateTime() {
        return sysProductCreateTime;
    }

    public void setSysProductCreateTime(String sysProductCreateTime) {
        this.sysProductCreateTime = sysProductCreateTime == null ? null : sysProductCreateTime.trim();
    }

    public Date getSysProductUpdateTime() {
        return sysProductUpdateTime;
    }

    public void setSysProductUpdateTime(Date sysProductUpdateTime) {
        this.sysProductUpdateTime = sysProductUpdateTime;
    }

    public String getSysProdcutChooseTime() {
        return sysProdcutChooseTime;
    }

    public void setSysProdcutChooseTime(String sysProdcutChooseTime) {
        this.sysProdcutChooseTime = sysProdcutChooseTime == null ? null : sysProdcutChooseTime.trim();
    }

    public Integer getSysProductDelFlag() {
        return sysProductDelFlag;
    }

    public void setSysProductDelFlag(Integer sysProductDelFlag) {
        this.sysProductDelFlag = sysProductDelFlag;
    }

	@Override
	public String toString() {
		return "SysProduct [sysProductId=" + sysProductId + ", sysProductName=" + sysProductName + ", sysProductPyCode="
				+ sysProductPyCode + ", sysProductPyName=" + sysProductPyName + ", sysProductState=" + sysProductState
				+ ", sysProductUnitName=" + sysProductUnitName + ", sysProductPrice=" + sysProductPrice
				+ ", sysProductImgUrl=" + sysProductImgUrl + ", sysProductCreateTime=" + sysProductCreateTime
				+ ", sysProductUpdateTime=" + sysProductUpdateTime + ", sysProdcutChooseTime=" + sysProdcutChooseTime
				+ ", sysProductDelFlag=" + sysProductDelFlag + ", sysProductCount=" + sysProductCount
				+ ", sysProductSalePrice=" + sysProductSalePrice + ", sysProductOrderNumber=" + sysProductOrderNumber
				+ ", sysProductProductTypeId=" + sysProductProductTypeId + ", sysProductTypeName=" + sysProductTypeName
				+ ", betOrderProductUnivalentRemark=" + betOrderProductUnivalentRemark + ", sysProductStaffBidPrice="
				+ sysProductStaffBidPrice + ", sysProductOrdinaryBidPrice=" + sysProductOrdinaryBidPrice + "]";
	}
    
    
}