package com.vieagr.distribution.entity;

import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

/**
 * 送货人
 * @author master
 *
 */
public class SysSender extends BaseEntity {
    /**
     * 送货人id
     * 表字段 : sys_sender.sys_sender_id
     */
    private String sysSenderId;

    /**
     * 送货人姓名
     * 表字段 : sys_sender.sys_sender_name
     */
    private String sysSenderName;

    /**
     * 送货人手机号码
     * 表字段 : sys_sender.sys_sender_mobile_number
     */
    private String sysSenderMobileNumber;

    /**
     * 送货人状态，1、启用，2、禁用
     * 表字段 : sys_sender.sys_sender_state
     */
    private Integer sysSenderState;

    /**
     * 送货人照片地址
     * 表字段 : sys_sender.sys_sender_img_url
     */
    private String sysSenderImgUrl;

    /**
     * 送货人信息创建时间
     * 表字段 : sys_sender.sys_sender_create_time
     */
    private String sysSenderCreateTime;

    /**
     * 送货人信息更新时间
     * 表字段 : sys_sender.sys_sender_update_time
     */
    private Date sysSenderUpdateTime;

    /**
     * 送货人删除标记，1、未删除，2、已删除
     * 表字段 : sys_sender.sys_sender_del_flag
     */
    private Integer sysSenderDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_sender
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getSysSenderId() {
        return sysSenderId;
    }

    public void setSysSenderId(String sysSenderId) {
        this.sysSenderId = sysSenderId == null ? null : sysSenderId.trim();
    }

    public String getSysSenderName() {
        return sysSenderName;
    }

    public void setSysSenderName(String sysSenderName) {
        this.sysSenderName = sysSenderName == null ? null : sysSenderName.trim();
    }

    public String getSysSenderMobileNumber() {
        return sysSenderMobileNumber;
    }

    public void setSysSenderMobileNumber(String sysSenderMobileNumber) {
        this.sysSenderMobileNumber = sysSenderMobileNumber == null ? null : sysSenderMobileNumber.trim();
    }

    public Integer getSysSenderState() {
        return sysSenderState;
    }

    public void setSysSenderState(Integer sysSenderState) {
        this.sysSenderState = sysSenderState;
    }

    public String getSysSenderImgUrl() {
        return sysSenderImgUrl;
    }

    public void setSysSenderImgUrl(String sysSenderImgUrl) {
        this.sysSenderImgUrl = sysSenderImgUrl == null ? null : sysSenderImgUrl.trim();
    }

    public String getSysSenderCreateTime() {
        return sysSenderCreateTime;
    }

    public void setSysSenderCreateTime(String sysSenderCreateTime) {
        this.sysSenderCreateTime = sysSenderCreateTime == null ? null : sysSenderCreateTime.trim();
    }

    public Date getSysSenderUpdateTime() {
        return sysSenderUpdateTime;
    }

    public void setSysSenderUpdateTime(Date sysSenderUpdateTime) {
        this.sysSenderUpdateTime = sysSenderUpdateTime;
    }

    public Integer getSysSenderDelFlag() {
        return sysSenderDelFlag;
    }

    public void setSysSenderDelFlag(Integer sysSenderDelFlag) {
        this.sysSenderDelFlag = sysSenderDelFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysSenderId=").append(sysSenderId);
        sb.append(", sysSenderName=").append(sysSenderName);
        sb.append(", sysSenderMobileNumber=").append(sysSenderMobileNumber);
        sb.append(", sysSenderState=").append(sysSenderState);
        sb.append(", sysSenderImgUrl=").append(sysSenderImgUrl);
        sb.append(", sysSenderCreateTime=").append(sysSenderCreateTime);
        sb.append(", sysSenderUpdateTime=").append(sysSenderUpdateTime);
        sb.append(", sysSenderDelFlag=").append(sysSenderDelFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}