package com.vieagr.distribution.entity;

import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

/**
 * 登录用户
 * @author master
 *
 */
public class SysUser extends BaseEntity {
    /**
     * 用户主键Id
     * 表字段 : sys_user.sys_user_id
     */
    private String sysUserId;

    /**
     * 用户名
     * 表字段 : sys_user.sys_user_name
     */
    private String sysUserName;

    /**
     * 用户登录密码
     * 表字段 : sys_user.sys_user_password
     */
    private String sysUserPassword;

    /**
     * 用户性别，1、男，2、女
     * 表字段 : sys_user.sys_user_sex
     */
    private Integer sysUserSex;

    /**
     * 用户年龄
     * 表字段 : sys_user.sys_user_age
     */
    private Integer sysUserAge;

    /**
     * 用户真实姓名
     * 表字段 : sys_user.sys_user_real_name
     */
    private String sysUserRealName;

    /**
     * 手机号码
     * 表字段 : sys_user.sys_user_mobile_number
     */
    private String sysUserMobileNumber;

    /**
     * 用户类型，1、超级管理员，2、普通用户
     * 表字段 : sys_user.sys_user_type
     */
    private Integer sysUserType;

    /**
     * 状态，1、启用，2、禁用
     * 表字段 : sys_user.sys_user_state
     */
    private Integer sysUserState;

    /**
     * 用户照片地址
     * 表字段 : sys_user.sys_user_img_url
     */
    private String sysUserImgUrl;

    /**
     * 创建时间
     * 表字段 : sys_user.sys_user_create_time
     */
    private String sysUserCreateTime;

    /**
     * 更新时间
     * 表字段 : sys_user.sys_user_update_time
     */
    private Date sysUserUpdateTime;

    /**
     * 作废删除标记,1、未删除，2、已删除
     * 表字段 : sys_user.sys_user_del_flag
     */
    private Integer sysUserDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getSysUserId() {
        return sysUserId;
    }

    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId == null ? null : sysUserId.trim();
    }

    public String getSysUserName() {
        return sysUserName;
    }

    public void setSysUserName(String sysUserName) {
        this.sysUserName = sysUserName == null ? null : sysUserName.trim();
    }

    public String getSysUserPassword() {
        return sysUserPassword;
    }

    public void setSysUserPassword(String sysUserPassword) {
        this.sysUserPassword = sysUserPassword == null ? null : sysUserPassword.trim();
    }

    public Integer getSysUserSex() {
        return sysUserSex;
    }

    public void setSysUserSex(Integer sysUserSex) {
        this.sysUserSex = sysUserSex;
    }

    public Integer getSysUserAge() {
        return sysUserAge;
    }

    public void setSysUserAge(Integer sysUserAge) {
        this.sysUserAge = sysUserAge;
    }

    public String getSysUserRealName() {
        return sysUserRealName;
    }

    public void setSysUserRealName(String sysUserRealName) {
        this.sysUserRealName = sysUserRealName == null ? null : sysUserRealName.trim();
    }

    public String getSysUserMobileNumber() {
        return sysUserMobileNumber;
    }

    public void setSysUserMobileNumber(String sysUserMobileNumber) {
        this.sysUserMobileNumber = sysUserMobileNumber == null ? null : sysUserMobileNumber.trim();
    }

    public Integer getSysUserType() {
        return sysUserType;
    }

    public void setSysUserType(Integer sysUserType) {
        this.sysUserType = sysUserType;
    }

    public Integer getSysUserState() {
        return sysUserState;
    }

    public void setSysUserState(Integer sysUserState) {
        this.sysUserState = sysUserState;
    }

    public String getSysUserImgUrl() {
        return sysUserImgUrl;
    }

    public void setSysUserImgUrl(String sysUserImgUrl) {
        this.sysUserImgUrl = sysUserImgUrl == null ? null : sysUserImgUrl.trim();
    }

    public String getSysUserCreateTime() {
        return sysUserCreateTime;
    }

    public void setSysUserCreateTime(String sysUserCreateTime) {
        this.sysUserCreateTime = sysUserCreateTime == null ? null : sysUserCreateTime.trim();
    }

    public Date getSysUserUpdateTime() {
        return sysUserUpdateTime;
    }

    public void setSysUserUpdateTime(Date sysUserUpdateTime) {
        this.sysUserUpdateTime = sysUserUpdateTime;
    }

    public Integer getSysUserDelFlag() {
        return sysUserDelFlag;
    }

    public void setSysUserDelFlag(Integer sysUserDelFlag) {
        this.sysUserDelFlag = sysUserDelFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysUserId=").append(sysUserId);
        sb.append(", sysUserName=").append(sysUserName);
        sb.append(", sysUserPassword=").append(sysUserPassword);
        sb.append(", sysUserSex=").append(sysUserSex);
        sb.append(", sysUserAge=").append(sysUserAge);
        sb.append(", sysUserRealName=").append(sysUserRealName);
        sb.append(", sysUserMobileNumber=").append(sysUserMobileNumber);
        sb.append(", sysUserType=").append(sysUserType);
        sb.append(", sysUserState=").append(sysUserState);
        sb.append(", sysUserImgUrl=").append(sysUserImgUrl);
        sb.append(", sysUserCreateTime=").append(sysUserCreateTime);
        sb.append(", sysUserUpdateTime=").append(sysUserUpdateTime);
        sb.append(", sysUserDelFlag=").append(sysUserDelFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}