package com.vieagr.distribution.entity;

import java.util.Date;

import com.vieagr.distribution.entity.base.BaseEntity;

/**
 * 送货车辆
 * @author master
 *
 */
public class SysVehicles extends BaseEntity {
    /**
     * 车辆主键id
     * 表字段 : sys_vehicles.sys_vehicles_id
     */
    private String sysVehiclesId;

    /**
     * 车牌号
     * 表字段 : sys_vehicles.sys_vehicles_plate_number
     */
    private String sysVehiclesPlateNumber;

    /**
     * 车辆类型，1、小型货车，2、中型货车，3、大型货车，4其他
     * 表字段 : sys_vehicles.sys_vehicles_type
     */
    private Integer sysVehiclesType;

    /**
     * 车辆信息描述
     * 表字段 : sys_vehicles.sys_vehicles_desc
     */
    private String sysVehiclesDesc;

    /**
     * 车辆等级，1、普通型，2、豪华型
     * 表字段 : sys_vehicles.sys_vehicles_grade
     */
    private Integer sysVehiclesGrade;

    /**
     * 车辆注册人姓名
     * 表字段 : sys_vehicles.sys_vehicles_register_name
     */
    private String sysVehiclesRegisterName;

    /**
     * 车辆注册人手机号码
     * 表字段 : sys_vehicles.sys_vehicles_register_mobile
     */
    private String sysVehiclesRegisterMobile;

    /**
     * 车辆照片地址
     * 表字段 : sys_vehicles.sys_vehicles_img_url
     */
    private String sysVehiclesImgUrl;

    /**
     * 车辆创建时间
     * 表字段 : sys_vehicles.sys_vehicles_create_time
     */
    private String sysVehiclesCreateTime;

    /**
     * 车辆更新时间
     * 表字段 : sys_vehicles.sys_vehicles_update_time
     */
    private Date sysVehiclesUpdateTime;

    /**
     * 车辆状态，1、启用，2、禁用
     * 表字段 : sys_vehicles.sys_vehicles_state
     */
    private Integer sysVehiclesState;

    /**
     * 车辆删除标记，1、未删除，2、已删除
     * 表字段 : sys_vehicles.sys_vehicles_del_flag
     */
    private Integer sysVehiclesDelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_vehicles
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getSysVehiclesId() {
        return sysVehiclesId;
    }

    public void setSysVehiclesId(String sysVehiclesId) {
        this.sysVehiclesId = sysVehiclesId == null ? null : sysVehiclesId.trim();
    }

    public String getSysVehiclesPlateNumber() {
        return sysVehiclesPlateNumber;
    }

    public void setSysVehiclesPlateNumber(String sysVehiclesPlateNumber) {
        this.sysVehiclesPlateNumber = sysVehiclesPlateNumber == null ? null : sysVehiclesPlateNumber.trim();
    }

    public Integer getSysVehiclesType() {
        return sysVehiclesType;
    }

    public void setSysVehiclesType(Integer sysVehiclesType) {
        this.sysVehiclesType = sysVehiclesType;
    }

    public String getSysVehiclesDesc() {
        return sysVehiclesDesc;
    }

    public void setSysVehiclesDesc(String sysVehiclesDesc) {
        this.sysVehiclesDesc = sysVehiclesDesc == null ? null : sysVehiclesDesc.trim();
    }

    public Integer getSysVehiclesGrade() {
        return sysVehiclesGrade;
    }

    public void setSysVehiclesGrade(Integer sysVehiclesGrade) {
        this.sysVehiclesGrade = sysVehiclesGrade;
    }

    public String getSysVehiclesRegisterName() {
        return sysVehiclesRegisterName;
    }

    public void setSysVehiclesRegisterName(String sysVehiclesRegisterName) {
        this.sysVehiclesRegisterName = sysVehiclesRegisterName == null ? null : sysVehiclesRegisterName.trim();
    }

    public String getSysVehiclesRegisterMobile() {
        return sysVehiclesRegisterMobile;
    }

    public void setSysVehiclesRegisterMobile(String sysVehiclesRegisterMobile) {
        this.sysVehiclesRegisterMobile = sysVehiclesRegisterMobile == null ? null : sysVehiclesRegisterMobile.trim();
    }

    public String getSysVehiclesImgUrl() {
        return sysVehiclesImgUrl;
    }

    public void setSysVehiclesImgUrl(String sysVehiclesImgUrl) {
        this.sysVehiclesImgUrl = sysVehiclesImgUrl == null ? null : sysVehiclesImgUrl.trim();
    }

    public String getSysVehiclesCreateTime() {
        return sysVehiclesCreateTime;
    }

    public void setSysVehiclesCreateTime(String sysVehiclesCreateTime) {
        this.sysVehiclesCreateTime = sysVehiclesCreateTime == null ? null : sysVehiclesCreateTime.trim();
    }

    public Date getSysVehiclesUpdateTime() {
        return sysVehiclesUpdateTime;
    }

    public void setSysVehiclesUpdateTime(Date sysVehiclesUpdateTime) {
        this.sysVehiclesUpdateTime = sysVehiclesUpdateTime;
    }

    public Integer getSysVehiclesState() {
        return sysVehiclesState;
    }

    public void setSysVehiclesState(Integer sysVehiclesState) {
        this.sysVehiclesState = sysVehiclesState;
    }

    public Integer getSysVehiclesDelFlag() {
        return sysVehiclesDelFlag;
    }

    public void setSysVehiclesDelFlag(Integer sysVehiclesDelFlag) {
        this.sysVehiclesDelFlag = sysVehiclesDelFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysVehiclesId=").append(sysVehiclesId);
        sb.append(", sysVehiclesPlateNumber=").append(sysVehiclesPlateNumber);
        sb.append(", sysVehiclesType=").append(sysVehiclesType);
        sb.append(", sysVehiclesDesc=").append(sysVehiclesDesc);
        sb.append(", sysVehiclesGrade=").append(sysVehiclesGrade);
        sb.append(", sysVehiclesRegisterName=").append(sysVehiclesRegisterName);
        sb.append(", sysVehiclesRegisterMobile=").append(sysVehiclesRegisterMobile);
        sb.append(", sysVehiclesImgUrl=").append(sysVehiclesImgUrl);
        sb.append(", sysVehiclesCreateTime=").append(sysVehiclesCreateTime);
        sb.append(", sysVehiclesUpdateTime=").append(sysVehiclesUpdateTime);
        sb.append(", sysVehiclesState=").append(sysVehiclesState);
        sb.append(", sysVehiclesDelFlag=").append(sysVehiclesDelFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}