package com.cqq.leisure.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActiveExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public ActiveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActiveIdIsNull() {
            addCriterion("ACTIVE_ID is null");
            return (Criteria) this;
        }

        public Criteria andActiveIdIsNotNull() {
            addCriterion("ACTIVE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andActiveIdEqualTo(Integer value) {
            addCriterion("ACTIVE_ID =", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdNotEqualTo(Integer value) {
            addCriterion("ACTIVE_ID <>", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdGreaterThan(Integer value) {
            addCriterion("ACTIVE_ID >", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE_ID >=", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdLessThan(Integer value) {
            addCriterion("ACTIVE_ID <", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdLessThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE_ID <=", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdIn(List<Integer> values) {
            addCriterion("ACTIVE_ID in", values, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdNotIn(List<Integer> values) {
            addCriterion("ACTIVE_ID not in", values, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE_ID between", value1, value2, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE_ID not between", value1, value2, "activeId");
            return (Criteria) this;
        }

        public Criteria andTagIdIsNull() {
            addCriterion("TAG_ID is null");
            return (Criteria) this;
        }

        public Criteria andTagIdIsNotNull() {
            addCriterion("TAG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTagIdEqualTo(Integer value) {
            addCriterion("TAG_ID =", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotEqualTo(Integer value) {
            addCriterion("TAG_ID <>", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdGreaterThan(Integer value) {
            addCriterion("TAG_ID >", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TAG_ID >=", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdLessThan(Integer value) {
            addCriterion("TAG_ID <", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdLessThanOrEqualTo(Integer value) {
            addCriterion("TAG_ID <=", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdIn(List<Integer> values) {
            addCriterion("TAG_ID in", values, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotIn(List<Integer> values) {
            addCriterion("TAG_ID not in", values, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdBetween(Integer value1, Integer value2) {
            addCriterion("TAG_ID between", value1, value2, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TAG_ID not between", value1, value2, "tagId");
            return (Criteria) this;
        }

        public Criteria andActiveNameIsNull() {
            addCriterion("ACTIVE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andActiveNameIsNotNull() {
            addCriterion("ACTIVE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andActiveNameEqualTo(String value) {
            addCriterion("ACTIVE_NAME =", value, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameNotEqualTo(String value) {
            addCriterion("ACTIVE_NAME <>", value, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameGreaterThan(String value) {
            addCriterion("ACTIVE_NAME >", value, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_NAME >=", value, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameLessThan(String value) {
            addCriterion("ACTIVE_NAME <", value, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_NAME <=", value, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameLike(String value) {
            addCriterion("ACTIVE_NAME like", value, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameNotLike(String value) {
            addCriterion("ACTIVE_NAME not like", value, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameIn(List<String> values) {
            addCriterion("ACTIVE_NAME in", values, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameNotIn(List<String> values) {
            addCriterion("ACTIVE_NAME not in", values, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameBetween(String value1, String value2) {
            addCriterion("ACTIVE_NAME between", value1, value2, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveNameNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_NAME not between", value1, value2, "activeName");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlIsNull() {
            addCriterion("ACTIVE_ICON_URL is null");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlIsNotNull() {
            addCriterion("ACTIVE_ICON_URL is not null");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlEqualTo(String value) {
            addCriterion("ACTIVE_ICON_URL =", value, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlNotEqualTo(String value) {
            addCriterion("ACTIVE_ICON_URL <>", value, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlGreaterThan(String value) {
            addCriterion("ACTIVE_ICON_URL >", value, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_ICON_URL >=", value, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlLessThan(String value) {
            addCriterion("ACTIVE_ICON_URL <", value, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_ICON_URL <=", value, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlLike(String value) {
            addCriterion("ACTIVE_ICON_URL like", value, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlNotLike(String value) {
            addCriterion("ACTIVE_ICON_URL not like", value, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlIn(List<String> values) {
            addCriterion("ACTIVE_ICON_URL in", values, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlNotIn(List<String> values) {
            addCriterion("ACTIVE_ICON_URL not in", values, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlBetween(String value1, String value2) {
            addCriterion("ACTIVE_ICON_URL between", value1, value2, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveIconUrlNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_ICON_URL not between", value1, value2, "activeIconUrl");
            return (Criteria) this;
        }

        public Criteria andActiveTypeIsNull() {
            addCriterion("ACTIVE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andActiveTypeIsNotNull() {
            addCriterion("ACTIVE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andActiveTypeEqualTo(String value) {
            addCriterion("ACTIVE_TYPE =", value, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeNotEqualTo(String value) {
            addCriterion("ACTIVE_TYPE <>", value, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeGreaterThan(String value) {
            addCriterion("ACTIVE_TYPE >", value, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_TYPE >=", value, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeLessThan(String value) {
            addCriterion("ACTIVE_TYPE <", value, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_TYPE <=", value, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeLike(String value) {
            addCriterion("ACTIVE_TYPE like", value, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeNotLike(String value) {
            addCriterion("ACTIVE_TYPE not like", value, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeIn(List<String> values) {
            addCriterion("ACTIVE_TYPE in", values, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeNotIn(List<String> values) {
            addCriterion("ACTIVE_TYPE not in", values, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeBetween(String value1, String value2) {
            addCriterion("ACTIVE_TYPE between", value1, value2, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveTypeNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_TYPE not between", value1, value2, "activeType");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentIsNull() {
            addCriterion("ACTIVE_MAIN_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentIsNotNull() {
            addCriterion("ACTIVE_MAIN_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentEqualTo(String value) {
            addCriterion("ACTIVE_MAIN_CONTENT =", value, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentNotEqualTo(String value) {
            addCriterion("ACTIVE_MAIN_CONTENT <>", value, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentGreaterThan(String value) {
            addCriterion("ACTIVE_MAIN_CONTENT >", value, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_MAIN_CONTENT >=", value, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentLessThan(String value) {
            addCriterion("ACTIVE_MAIN_CONTENT <", value, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_MAIN_CONTENT <=", value, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentLike(String value) {
            addCriterion("ACTIVE_MAIN_CONTENT like", value, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentNotLike(String value) {
            addCriterion("ACTIVE_MAIN_CONTENT not like", value, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentIn(List<String> values) {
            addCriterion("ACTIVE_MAIN_CONTENT in", values, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentNotIn(List<String> values) {
            addCriterion("ACTIVE_MAIN_CONTENT not in", values, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentBetween(String value1, String value2) {
            addCriterion("ACTIVE_MAIN_CONTENT between", value1, value2, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveMainContentNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_MAIN_CONTENT not between", value1, value2, "activeMainContent");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeIsNull() {
            addCriterion("ACTIVE_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeIsNotNull() {
            addCriterion("ACTIVE_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeEqualTo(Date value) {
            addCriterion("ACTIVE_START_TIME =", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeNotEqualTo(Date value) {
            addCriterion("ACTIVE_START_TIME <>", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeGreaterThan(Date value) {
            addCriterion("ACTIVE_START_TIME >", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTIVE_START_TIME >=", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeLessThan(Date value) {
            addCriterion("ACTIVE_START_TIME <", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("ACTIVE_START_TIME <=", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeIn(List<Date> values) {
            addCriterion("ACTIVE_START_TIME in", values, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeNotIn(List<Date> values) {
            addCriterion("ACTIVE_START_TIME not in", values, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeBetween(Date value1, Date value2) {
            addCriterion("ACTIVE_START_TIME between", value1, value2, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("ACTIVE_START_TIME not between", value1, value2, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeIsNull() {
            addCriterion("ACTIVE_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeIsNotNull() {
            addCriterion("ACTIVE_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeEqualTo(Date value) {
            addCriterion("ACTIVE_END_TIME =", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeNotEqualTo(Date value) {
            addCriterion("ACTIVE_END_TIME <>", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeGreaterThan(Date value) {
            addCriterion("ACTIVE_END_TIME >", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTIVE_END_TIME >=", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeLessThan(Date value) {
            addCriterion("ACTIVE_END_TIME <", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("ACTIVE_END_TIME <=", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeIn(List<Date> values) {
            addCriterion("ACTIVE_END_TIME in", values, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeNotIn(List<Date> values) {
            addCriterion("ACTIVE_END_TIME not in", values, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeBetween(Date value1, Date value2) {
            addCriterion("ACTIVE_END_TIME between", value1, value2, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("ACTIVE_END_TIME not between", value1, value2, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveAddressIsNull() {
            addCriterion("ACTIVE_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andActiveAddressIsNotNull() {
            addCriterion("ACTIVE_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andActiveAddressEqualTo(String value) {
            addCriterion("ACTIVE_ADDRESS =", value, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressNotEqualTo(String value) {
            addCriterion("ACTIVE_ADDRESS <>", value, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressGreaterThan(String value) {
            addCriterion("ACTIVE_ADDRESS >", value, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_ADDRESS >=", value, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressLessThan(String value) {
            addCriterion("ACTIVE_ADDRESS <", value, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_ADDRESS <=", value, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressLike(String value) {
            addCriterion("ACTIVE_ADDRESS like", value, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressNotLike(String value) {
            addCriterion("ACTIVE_ADDRESS not like", value, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressIn(List<String> values) {
            addCriterion("ACTIVE_ADDRESS in", values, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressNotIn(List<String> values) {
            addCriterion("ACTIVE_ADDRESS not in", values, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressBetween(String value1, String value2) {
            addCriterion("ACTIVE_ADDRESS between", value1, value2, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveAddressNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_ADDRESS not between", value1, value2, "activeAddress");
            return (Criteria) this;
        }

        public Criteria andActiveLogIsNull() {
            addCriterion("ACTIVE_LOG is null");
            return (Criteria) this;
        }

        public Criteria andActiveLogIsNotNull() {
            addCriterion("ACTIVE_LOG is not null");
            return (Criteria) this;
        }

        public Criteria andActiveLogEqualTo(String value) {
            addCriterion("ACTIVE_LOG =", value, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogNotEqualTo(String value) {
            addCriterion("ACTIVE_LOG <>", value, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogGreaterThan(String value) {
            addCriterion("ACTIVE_LOG >", value, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_LOG >=", value, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogLessThan(String value) {
            addCriterion("ACTIVE_LOG <", value, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_LOG <=", value, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogLike(String value) {
            addCriterion("ACTIVE_LOG like", value, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogNotLike(String value) {
            addCriterion("ACTIVE_LOG not like", value, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogIn(List<String> values) {
            addCriterion("ACTIVE_LOG in", values, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogNotIn(List<String> values) {
            addCriterion("ACTIVE_LOG not in", values, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogBetween(String value1, String value2) {
            addCriterion("ACTIVE_LOG between", value1, value2, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLogNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_LOG not between", value1, value2, "activeLog");
            return (Criteria) this;
        }

        public Criteria andActiveLatIsNull() {
            addCriterion("ACTIVE_LAT is null");
            return (Criteria) this;
        }

        public Criteria andActiveLatIsNotNull() {
            addCriterion("ACTIVE_LAT is not null");
            return (Criteria) this;
        }

        public Criteria andActiveLatEqualTo(String value) {
            addCriterion("ACTIVE_LAT =", value, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatNotEqualTo(String value) {
            addCriterion("ACTIVE_LAT <>", value, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatGreaterThan(String value) {
            addCriterion("ACTIVE_LAT >", value, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_LAT >=", value, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatLessThan(String value) {
            addCriterion("ACTIVE_LAT <", value, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_LAT <=", value, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatLike(String value) {
            addCriterion("ACTIVE_LAT like", value, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatNotLike(String value) {
            addCriterion("ACTIVE_LAT not like", value, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatIn(List<String> values) {
            addCriterion("ACTIVE_LAT in", values, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatNotIn(List<String> values) {
            addCriterion("ACTIVE_LAT not in", values, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatBetween(String value1, String value2) {
            addCriterion("ACTIVE_LAT between", value1, value2, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveLatNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_LAT not between", value1, value2, "activeLat");
            return (Criteria) this;
        }

        public Criteria andActiveStateIsNull() {
            addCriterion("ACTIVE_STATE is null");
            return (Criteria) this;
        }

        public Criteria andActiveStateIsNotNull() {
            addCriterion("ACTIVE_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andActiveStateEqualTo(Integer value) {
            addCriterion("ACTIVE_STATE =", value, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateNotEqualTo(Integer value) {
            addCriterion("ACTIVE_STATE <>", value, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateGreaterThan(Integer value) {
            addCriterion("ACTIVE_STATE >", value, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE_STATE >=", value, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateLessThan(Integer value) {
            addCriterion("ACTIVE_STATE <", value, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateLessThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE_STATE <=", value, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateIn(List<Integer> values) {
            addCriterion("ACTIVE_STATE in", values, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateNotIn(List<Integer> values) {
            addCriterion("ACTIVE_STATE not in", values, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE_STATE between", value1, value2, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveStateNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE_STATE not between", value1, value2, "activeState");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeIsNull() {
            addCriterion("ACTIVE_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeIsNotNull() {
            addCriterion("ACTIVE_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeEqualTo(Date value) {
            addCriterion("ACTIVE_CREATE_TIME =", value, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeNotEqualTo(Date value) {
            addCriterion("ACTIVE_CREATE_TIME <>", value, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeGreaterThan(Date value) {
            addCriterion("ACTIVE_CREATE_TIME >", value, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTIVE_CREATE_TIME >=", value, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeLessThan(Date value) {
            addCriterion("ACTIVE_CREATE_TIME <", value, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("ACTIVE_CREATE_TIME <=", value, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeIn(List<Date> values) {
            addCriterion("ACTIVE_CREATE_TIME in", values, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeNotIn(List<Date> values) {
            addCriterion("ACTIVE_CREATE_TIME not in", values, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeBetween(Date value1, Date value2) {
            addCriterion("ACTIVE_CREATE_TIME between", value1, value2, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("ACTIVE_CREATE_TIME not between", value1, value2, "activeCreateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeIsNull() {
            addCriterion("ACTIVE_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeIsNotNull() {
            addCriterion("ACTIVE_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeEqualTo(Date value) {
            addCriterion("ACTIVE_UPDATE_TIME =", value, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeNotEqualTo(Date value) {
            addCriterion("ACTIVE_UPDATE_TIME <>", value, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeGreaterThan(Date value) {
            addCriterion("ACTIVE_UPDATE_TIME >", value, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTIVE_UPDATE_TIME >=", value, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeLessThan(Date value) {
            addCriterion("ACTIVE_UPDATE_TIME <", value, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("ACTIVE_UPDATE_TIME <=", value, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeIn(List<Date> values) {
            addCriterion("ACTIVE_UPDATE_TIME in", values, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeNotIn(List<Date> values) {
            addCriterion("ACTIVE_UPDATE_TIME not in", values, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("ACTIVE_UPDATE_TIME between", value1, value2, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("ACTIVE_UPDATE_TIME not between", value1, value2, "activeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andActiveTagIsNull() {
            addCriterion("ACTIVE_TAG is null");
            return (Criteria) this;
        }

        public Criteria andActiveTagIsNotNull() {
            addCriterion("ACTIVE_TAG is not null");
            return (Criteria) this;
        }

        public Criteria andActiveTagEqualTo(String value) {
            addCriterion("ACTIVE_TAG =", value, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagNotEqualTo(String value) {
            addCriterion("ACTIVE_TAG <>", value, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagGreaterThan(String value) {
            addCriterion("ACTIVE_TAG >", value, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_TAG >=", value, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagLessThan(String value) {
            addCriterion("ACTIVE_TAG <", value, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_TAG <=", value, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagLike(String value) {
            addCriterion("ACTIVE_TAG like", value, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagNotLike(String value) {
            addCriterion("ACTIVE_TAG not like", value, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagIn(List<String> values) {
            addCriterion("ACTIVE_TAG in", values, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagNotIn(List<String> values) {
            addCriterion("ACTIVE_TAG not in", values, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagBetween(String value1, String value2) {
            addCriterion("ACTIVE_TAG between", value1, value2, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveTagNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_TAG not between", value1, value2, "activeTag");
            return (Criteria) this;
        }

        public Criteria andActiveSortIsNull() {
            addCriterion("ACTIVE_SORT is null");
            return (Criteria) this;
        }

        public Criteria andActiveSortIsNotNull() {
            addCriterion("ACTIVE_SORT is not null");
            return (Criteria) this;
        }

        public Criteria andActiveSortEqualTo(Integer value) {
            addCriterion("ACTIVE_SORT =", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortNotEqualTo(Integer value) {
            addCriterion("ACTIVE_SORT <>", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortGreaterThan(Integer value) {
            addCriterion("ACTIVE_SORT >", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE_SORT >=", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortLessThan(Integer value) {
            addCriterion("ACTIVE_SORT <", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortLessThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE_SORT <=", value, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortIn(List<Integer> values) {
            addCriterion("ACTIVE_SORT in", values, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortNotIn(List<Integer> values) {
            addCriterion("ACTIVE_SORT not in", values, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE_SORT between", value1, value2, "activeSort");
            return (Criteria) this;
        }

        public Criteria andActiveSortNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE_SORT not between", value1, value2, "activeSort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table active
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table active
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}