package com.cqq.leisure.entity;

import java.util.Date;

public class Active {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String activeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String activeIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String activeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String activeMainContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date activeStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date activeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String activeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String activeLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String activeLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer activeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date activeCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date activeUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String activeTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.ACTIVE_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer activeSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_ID
     *
     * @return the value of active.ACTIVE_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_ID
     *
     * @param activeId the value for active.ACTIVE_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveId(Integer activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.TAG_ID
     *
     * @return the value of active.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.TAG_ID
     *
     * @param tagId the value for active.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_NAME
     *
     * @return the value of active.ACTIVE_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getActiveName() {
        return activeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_NAME
     *
     * @param activeName the value for active.ACTIVE_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveName(String activeName) {
        this.activeName = activeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_ICON_URL
     *
     * @return the value of active.ACTIVE_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getActiveIconUrl() {
        return activeIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_ICON_URL
     *
     * @param activeIconUrl the value for active.ACTIVE_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveIconUrl(String activeIconUrl) {
        this.activeIconUrl = activeIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_TYPE
     *
     * @return the value of active.ACTIVE_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getActiveType() {
        return activeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_TYPE
     *
     * @param activeType the value for active.ACTIVE_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveType(String activeType) {
        this.activeType = activeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_MAIN_CONTENT
     *
     * @return the value of active.ACTIVE_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getActiveMainContent() {
        return activeMainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_MAIN_CONTENT
     *
     * @param activeMainContent the value for active.ACTIVE_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveMainContent(String activeMainContent) {
        this.activeMainContent = activeMainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_START_TIME
     *
     * @return the value of active.ACTIVE_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getActiveStartTime() {
        return activeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_START_TIME
     *
     * @param activeStartTime the value for active.ACTIVE_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveStartTime(Date activeStartTime) {
        this.activeStartTime = activeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_END_TIME
     *
     * @return the value of active.ACTIVE_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getActiveEndTime() {
        return activeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_END_TIME
     *
     * @param activeEndTime the value for active.ACTIVE_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveEndTime(Date activeEndTime) {
        this.activeEndTime = activeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_ADDRESS
     *
     * @return the value of active.ACTIVE_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getActiveAddress() {
        return activeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_ADDRESS
     *
     * @param activeAddress the value for active.ACTIVE_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveAddress(String activeAddress) {
        this.activeAddress = activeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_LOG
     *
     * @return the value of active.ACTIVE_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getActiveLog() {
        return activeLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_LOG
     *
     * @param activeLog the value for active.ACTIVE_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveLog(String activeLog) {
        this.activeLog = activeLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_LAT
     *
     * @return the value of active.ACTIVE_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getActiveLat() {
        return activeLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_LAT
     *
     * @param activeLat the value for active.ACTIVE_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveLat(String activeLat) {
        this.activeLat = activeLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_STATE
     *
     * @return the value of active.ACTIVE_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getActiveState() {
        return activeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_STATE
     *
     * @param activeState the value for active.ACTIVE_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveState(Integer activeState) {
        this.activeState = activeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_CREATE_TIME
     *
     * @return the value of active.ACTIVE_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getActiveCreateTime() {
        return activeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_CREATE_TIME
     *
     * @param activeCreateTime the value for active.ACTIVE_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveCreateTime(Date activeCreateTime) {
        this.activeCreateTime = activeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_UPDATE_TIME
     *
     * @return the value of active.ACTIVE_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getActiveUpdateTime() {
        return activeUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_UPDATE_TIME
     *
     * @param activeUpdateTime the value for active.ACTIVE_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveUpdateTime(Date activeUpdateTime) {
        this.activeUpdateTime = activeUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_TAG
     *
     * @return the value of active.ACTIVE_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getActiveTag() {
        return activeTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_TAG
     *
     * @param activeTag the value for active.ACTIVE_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveTag(String activeTag) {
        this.activeTag = activeTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.ACTIVE_SORT
     *
     * @return the value of active.ACTIVE_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getActiveSort() {
        return activeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.ACTIVE_SORT
     *
     * @param activeSort the value for active.ACTIVE_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveSort(Integer activeSort) {
        this.activeSort = activeSort;
    }
}