package com.cqq.leisure.entity;

import java.util.Date;

public class HolidayPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer holidayPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String holidayPlanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String holidayPlanIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String holidayPlanStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date holidayPlanEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_DESC
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String holidayPlanDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_IMG_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String holidayPlanImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer holidayPlanState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date holidayPlanCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date holidayPlanUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAY_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String holidayPlayTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday_plan.HOLIDAY_PLAY_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer holidayPlaySort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_ID
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getHolidayPlanId() {
        return holidayPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_ID
     *
     * @param holidayPlanId the value for holiday_plan.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanId(Integer holidayPlanId) {
        this.holidayPlanId = holidayPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.TAG_ID
     *
     * @return the value of holiday_plan.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.TAG_ID
     *
     * @param tagId the value for holiday_plan.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_NAME
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getHolidayPlanName() {
        return holidayPlanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_NAME
     *
     * @param holidayPlanName the value for holiday_plan.HOLIDAY_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanName(String holidayPlanName) {
        this.holidayPlanName = holidayPlanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_ICON_URL
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getHolidayPlanIconUrl() {
        return holidayPlanIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_ICON_URL
     *
     * @param holidayPlanIconUrl the value for holiday_plan.HOLIDAY_PLAN_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanIconUrl(String holidayPlanIconUrl) {
        this.holidayPlanIconUrl = holidayPlanIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_START_TIME
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getHolidayPlanStartTime() {
        return holidayPlanStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_START_TIME
     *
     * @param holidayPlanStartTime the value for holiday_plan.HOLIDAY_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanStartTime(String holidayPlanStartTime) {
        this.holidayPlanStartTime = holidayPlanStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_END_TIME
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getHolidayPlanEndTime() {
        return holidayPlanEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_END_TIME
     *
     * @param holidayPlanEndTime the value for holiday_plan.HOLIDAY_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanEndTime(Date holidayPlanEndTime) {
        this.holidayPlanEndTime = holidayPlanEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_DESC
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_DESC
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getHolidayPlanDesc() {
        return holidayPlanDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_DESC
     *
     * @param holidayPlanDesc the value for holiday_plan.HOLIDAY_PLAN_DESC
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanDesc(String holidayPlanDesc) {
        this.holidayPlanDesc = holidayPlanDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_IMG_URL
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_IMG_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getHolidayPlanImgUrl() {
        return holidayPlanImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_IMG_URL
     *
     * @param holidayPlanImgUrl the value for holiday_plan.HOLIDAY_PLAN_IMG_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanImgUrl(String holidayPlanImgUrl) {
        this.holidayPlanImgUrl = holidayPlanImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_STATE
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getHolidayPlanState() {
        return holidayPlanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_STATE
     *
     * @param holidayPlanState the value for holiday_plan.HOLIDAY_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanState(Integer holidayPlanState) {
        this.holidayPlanState = holidayPlanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_CREATE_TIME
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getHolidayPlanCreateTime() {
        return holidayPlanCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_CREATE_TIME
     *
     * @param holidayPlanCreateTime the value for holiday_plan.HOLIDAY_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanCreateTime(Date holidayPlanCreateTime) {
        this.holidayPlanCreateTime = holidayPlanCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAN_UPDATE_TIME
     *
     * @return the value of holiday_plan.HOLIDAY_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getHolidayPlanUpdateTime() {
        return holidayPlanUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAN_UPDATE_TIME
     *
     * @param holidayPlanUpdateTime the value for holiday_plan.HOLIDAY_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanUpdateTime(Date holidayPlanUpdateTime) {
        this.holidayPlanUpdateTime = holidayPlanUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAY_TAG
     *
     * @return the value of holiday_plan.HOLIDAY_PLAY_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getHolidayPlayTag() {
        return holidayPlayTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAY_TAG
     *
     * @param holidayPlayTag the value for holiday_plan.HOLIDAY_PLAY_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlayTag(String holidayPlayTag) {
        this.holidayPlayTag = holidayPlayTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_plan.HOLIDAY_PLAY_SORT
     *
     * @return the value of holiday_plan.HOLIDAY_PLAY_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getHolidayPlaySort() {
        return holidayPlaySort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_plan.HOLIDAY_PLAY_SORT
     *
     * @param holidayPlaySort the value for holiday_plan.HOLIDAY_PLAY_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlaySort(Integer holidayPlaySort) {
        this.holidayPlaySort = holidayPlaySort;
    }
}