package com.cqq.leisure.entity;

import java.util.Date;

public class Images {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.IMAGES_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer imagesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer holidayPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.PROGRAM_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer programPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.ACTIVE_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.IMAGES_DESC
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String imagesDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.IMAGES_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String imagesUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.IMAGES_SUF_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String imagesSufContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.IMAGES_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer imagesState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.IMAGES_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date imagesCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.IMAGES_ID
     *
     * @return the value of images.IMAGES_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getImagesId() {
        return imagesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.IMAGES_ID
     *
     * @param imagesId the value for images.IMAGES_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setImagesId(Integer imagesId) {
        this.imagesId = imagesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.HOLIDAY_PLAN_ID
     *
     * @return the value of images.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getHolidayPlanId() {
        return holidayPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.HOLIDAY_PLAN_ID
     *
     * @param holidayPlanId the value for images.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanId(Integer holidayPlanId) {
        this.holidayPlanId = holidayPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.PROGRAM_PLAN_ID
     *
     * @return the value of images.PROGRAM_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getProgramPlanId() {
        return programPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.PROGRAM_PLAN_ID
     *
     * @param programPlanId the value for images.PROGRAM_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanId(Integer programPlanId) {
        this.programPlanId = programPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.ACTIVE_ID
     *
     * @return the value of images.ACTIVE_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.ACTIVE_ID
     *
     * @param activeId the value for images.ACTIVE_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setActiveId(Integer activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.IMAGES_DESC
     *
     * @return the value of images.IMAGES_DESC
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getImagesDesc() {
        return imagesDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.IMAGES_DESC
     *
     * @param imagesDesc the value for images.IMAGES_DESC
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setImagesDesc(String imagesDesc) {
        this.imagesDesc = imagesDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.IMAGES_URL
     *
     * @return the value of images.IMAGES_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getImagesUrl() {
        return imagesUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.IMAGES_URL
     *
     * @param imagesUrl the value for images.IMAGES_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setImagesUrl(String imagesUrl) {
        this.imagesUrl = imagesUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.IMAGES_SUF_CONTENT
     *
     * @return the value of images.IMAGES_SUF_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getImagesSufContent() {
        return imagesSufContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.IMAGES_SUF_CONTENT
     *
     * @param imagesSufContent the value for images.IMAGES_SUF_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setImagesSufContent(String imagesSufContent) {
        this.imagesSufContent = imagesSufContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.IMAGES_STATE
     *
     * @return the value of images.IMAGES_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getImagesState() {
        return imagesState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.IMAGES_STATE
     *
     * @param imagesState the value for images.IMAGES_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setImagesState(Integer imagesState) {
        this.imagesState = imagesState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.IMAGES_CREATE_TIME
     *
     * @return the value of images.IMAGES_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getImagesCreateTime() {
        return imagesCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.IMAGES_CREATE_TIME
     *
     * @param imagesCreateTime the value for images.IMAGES_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setImagesCreateTime(Date imagesCreateTime) {
        this.imagesCreateTime = imagesCreateTime;
    }
}