package com.cqq.leisure.entity;

import java.util.Date;

public class Merchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_LINKMAN
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_PHONE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_AD
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantAd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_GPS_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantGpsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_INTRO
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer merchantState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date merchantCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date merchantUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String merchantTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer merchantSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_ID
     *
     * @return the value of merchant.MERCHANT_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_ID
     *
     * @param merchantId the value for merchant.MERCHANT_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.TAG_ID
     *
     * @return the value of merchant.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.TAG_ID
     *
     * @param tagId the value for merchant.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_ICON_URL
     *
     * @return the value of merchant.MERCHANT_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantIconUrl() {
        return merchantIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_ICON_URL
     *
     * @param merchantIconUrl the value for merchant.MERCHANT_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantIconUrl(String merchantIconUrl) {
        this.merchantIconUrl = merchantIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_LINKMAN
     *
     * @return the value of merchant.MERCHANT_LINKMAN
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantLinkman() {
        return merchantLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_LINKMAN
     *
     * @param merchantLinkman the value for merchant.MERCHANT_LINKMAN
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantLinkman(String merchantLinkman) {
        this.merchantLinkman = merchantLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_PHONE
     *
     * @return the value of merchant.MERCHANT_PHONE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantPhone() {
        return merchantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_PHONE
     *
     * @param merchantPhone the value for merchant.MERCHANT_PHONE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantPhone(String merchantPhone) {
        this.merchantPhone = merchantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_ADDRESS
     *
     * @return the value of merchant.MERCHANT_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantAddress() {
        return merchantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_ADDRESS
     *
     * @param merchantAddress the value for merchant.MERCHANT_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantAddress(String merchantAddress) {
        this.merchantAddress = merchantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_AD
     *
     * @return the value of merchant.MERCHANT_AD
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantAd() {
        return merchantAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_AD
     *
     * @param merchantAd the value for merchant.MERCHANT_AD
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantAd(String merchantAd) {
        this.merchantAd = merchantAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_NAME
     *
     * @return the value of merchant.MERCHANT_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_NAME
     *
     * @param merchantName the value for merchant.MERCHANT_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_TYPE
     *
     * @return the value of merchant.MERCHANT_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantType() {
        return merchantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_TYPE
     *
     * @param merchantType the value for merchant.MERCHANT_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantType(String merchantType) {
        this.merchantType = merchantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_GPS_ADDRESS
     *
     * @return the value of merchant.MERCHANT_GPS_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantGpsAddress() {
        return merchantGpsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_GPS_ADDRESS
     *
     * @param merchantGpsAddress the value for merchant.MERCHANT_GPS_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantGpsAddress(String merchantGpsAddress) {
        this.merchantGpsAddress = merchantGpsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_LOG
     *
     * @return the value of merchant.MERCHANT_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantLog() {
        return merchantLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_LOG
     *
     * @param merchantLog the value for merchant.MERCHANT_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantLog(String merchantLog) {
        this.merchantLog = merchantLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_LAT
     *
     * @return the value of merchant.MERCHANT_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantLat() {
        return merchantLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_LAT
     *
     * @param merchantLat the value for merchant.MERCHANT_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantLat(String merchantLat) {
        this.merchantLat = merchantLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_INTRO
     *
     * @return the value of merchant.MERCHANT_INTRO
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantIntro() {
        return merchantIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_INTRO
     *
     * @param merchantIntro the value for merchant.MERCHANT_INTRO
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantIntro(String merchantIntro) {
        this.merchantIntro = merchantIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_STATE
     *
     * @return the value of merchant.MERCHANT_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getMerchantState() {
        return merchantState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_STATE
     *
     * @param merchantState the value for merchant.MERCHANT_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantState(Integer merchantState) {
        this.merchantState = merchantState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_CREATE_TIME
     *
     * @return the value of merchant.MERCHANT_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getMerchantCreateTime() {
        return merchantCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_CREATE_TIME
     *
     * @param merchantCreateTime the value for merchant.MERCHANT_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantCreateTime(Date merchantCreateTime) {
        this.merchantCreateTime = merchantCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_UPDATE_TIME
     *
     * @return the value of merchant.MERCHANT_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getMerchantUpdateTime() {
        return merchantUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_UPDATE_TIME
     *
     * @param merchantUpdateTime the value for merchant.MERCHANT_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantUpdateTime(Date merchantUpdateTime) {
        this.merchantUpdateTime = merchantUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_TAG
     *
     * @return the value of merchant.MERCHANT_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getMerchantTag() {
        return merchantTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_TAG
     *
     * @param merchantTag the value for merchant.MERCHANT_TAG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantTag(String merchantTag) {
        this.merchantTag = merchantTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_SORT
     *
     * @return the value of merchant.MERCHANT_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getMerchantSort() {
        return merchantSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_SORT
     *
     * @param merchantSort the value for merchant.MERCHANT_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setMerchantSort(Integer merchantSort) {
        this.merchantSort = merchantSort;
    }
}