package com.cqq.leisure.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MerchantExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public MerchantExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("MERCHANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("MERCHANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(String value) {
            addCriterion("MERCHANT_ID =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(String value) {
            addCriterion("MERCHANT_ID <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(String value) {
            addCriterion("MERCHANT_ID >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ID >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(String value) {
            addCriterion("MERCHANT_ID <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ID <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLike(String value) {
            addCriterion("MERCHANT_ID like", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotLike(String value) {
            addCriterion("MERCHANT_ID not like", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<String> values) {
            addCriterion("MERCHANT_ID in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<String> values) {
            addCriterion("MERCHANT_ID not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(String value1, String value2) {
            addCriterion("MERCHANT_ID between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_ID not between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andTagIdIsNull() {
            addCriterion("TAG_ID is null");
            return (Criteria) this;
        }

        public Criteria andTagIdIsNotNull() {
            addCriterion("TAG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTagIdEqualTo(Integer value) {
            addCriterion("TAG_ID =", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotEqualTo(Integer value) {
            addCriterion("TAG_ID <>", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdGreaterThan(Integer value) {
            addCriterion("TAG_ID >", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TAG_ID >=", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdLessThan(Integer value) {
            addCriterion("TAG_ID <", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdLessThanOrEqualTo(Integer value) {
            addCriterion("TAG_ID <=", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdIn(List<Integer> values) {
            addCriterion("TAG_ID in", values, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotIn(List<Integer> values) {
            addCriterion("TAG_ID not in", values, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdBetween(Integer value1, Integer value2) {
            addCriterion("TAG_ID between", value1, value2, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TAG_ID not between", value1, value2, "tagId");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlIsNull() {
            addCriterion("MERCHANT_ICON_URL is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlIsNotNull() {
            addCriterion("MERCHANT_ICON_URL is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlEqualTo(String value) {
            addCriterion("MERCHANT_ICON_URL =", value, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlNotEqualTo(String value) {
            addCriterion("MERCHANT_ICON_URL <>", value, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlGreaterThan(String value) {
            addCriterion("MERCHANT_ICON_URL >", value, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ICON_URL >=", value, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlLessThan(String value) {
            addCriterion("MERCHANT_ICON_URL <", value, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ICON_URL <=", value, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlLike(String value) {
            addCriterion("MERCHANT_ICON_URL like", value, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlNotLike(String value) {
            addCriterion("MERCHANT_ICON_URL not like", value, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlIn(List<String> values) {
            addCriterion("MERCHANT_ICON_URL in", values, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlNotIn(List<String> values) {
            addCriterion("MERCHANT_ICON_URL not in", values, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlBetween(String value1, String value2) {
            addCriterion("MERCHANT_ICON_URL between", value1, value2, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantIconUrlNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_ICON_URL not between", value1, value2, "merchantIconUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanIsNull() {
            addCriterion("MERCHANT_LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanIsNotNull() {
            addCriterion("MERCHANT_LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanEqualTo(String value) {
            addCriterion("MERCHANT_LINKMAN =", value, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanNotEqualTo(String value) {
            addCriterion("MERCHANT_LINKMAN <>", value, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanGreaterThan(String value) {
            addCriterion("MERCHANT_LINKMAN >", value, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_LINKMAN >=", value, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanLessThan(String value) {
            addCriterion("MERCHANT_LINKMAN <", value, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_LINKMAN <=", value, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanLike(String value) {
            addCriterion("MERCHANT_LINKMAN like", value, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanNotLike(String value) {
            addCriterion("MERCHANT_LINKMAN not like", value, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanIn(List<String> values) {
            addCriterion("MERCHANT_LINKMAN in", values, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanNotIn(List<String> values) {
            addCriterion("MERCHANT_LINKMAN not in", values, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanBetween(String value1, String value2) {
            addCriterion("MERCHANT_LINKMAN between", value1, value2, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantLinkmanNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_LINKMAN not between", value1, value2, "merchantLinkman");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneIsNull() {
            addCriterion("MERCHANT_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneIsNotNull() {
            addCriterion("MERCHANT_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneEqualTo(String value) {
            addCriterion("MERCHANT_PHONE =", value, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneNotEqualTo(String value) {
            addCriterion("MERCHANT_PHONE <>", value, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneGreaterThan(String value) {
            addCriterion("MERCHANT_PHONE >", value, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_PHONE >=", value, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneLessThan(String value) {
            addCriterion("MERCHANT_PHONE <", value, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_PHONE <=", value, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneLike(String value) {
            addCriterion("MERCHANT_PHONE like", value, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneNotLike(String value) {
            addCriterion("MERCHANT_PHONE not like", value, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneIn(List<String> values) {
            addCriterion("MERCHANT_PHONE in", values, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneNotIn(List<String> values) {
            addCriterion("MERCHANT_PHONE not in", values, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneBetween(String value1, String value2) {
            addCriterion("MERCHANT_PHONE between", value1, value2, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantPhoneNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_PHONE not between", value1, value2, "merchantPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressIsNull() {
            addCriterion("MERCHANT_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressIsNotNull() {
            addCriterion("MERCHANT_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressEqualTo(String value) {
            addCriterion("MERCHANT_ADDRESS =", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressNotEqualTo(String value) {
            addCriterion("MERCHANT_ADDRESS <>", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressGreaterThan(String value) {
            addCriterion("MERCHANT_ADDRESS >", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ADDRESS >=", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressLessThan(String value) {
            addCriterion("MERCHANT_ADDRESS <", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ADDRESS <=", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressLike(String value) {
            addCriterion("MERCHANT_ADDRESS like", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressNotLike(String value) {
            addCriterion("MERCHANT_ADDRESS not like", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressIn(List<String> values) {
            addCriterion("MERCHANT_ADDRESS in", values, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressNotIn(List<String> values) {
            addCriterion("MERCHANT_ADDRESS not in", values, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressBetween(String value1, String value2) {
            addCriterion("MERCHANT_ADDRESS between", value1, value2, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_ADDRESS not between", value1, value2, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAdIsNull() {
            addCriterion("MERCHANT_AD is null");
            return (Criteria) this;
        }

        public Criteria andMerchantAdIsNotNull() {
            addCriterion("MERCHANT_AD is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantAdEqualTo(String value) {
            addCriterion("MERCHANT_AD =", value, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdNotEqualTo(String value) {
            addCriterion("MERCHANT_AD <>", value, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdGreaterThan(String value) {
            addCriterion("MERCHANT_AD >", value, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_AD >=", value, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdLessThan(String value) {
            addCriterion("MERCHANT_AD <", value, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_AD <=", value, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdLike(String value) {
            addCriterion("MERCHANT_AD like", value, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdNotLike(String value) {
            addCriterion("MERCHANT_AD not like", value, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdIn(List<String> values) {
            addCriterion("MERCHANT_AD in", values, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdNotIn(List<String> values) {
            addCriterion("MERCHANT_AD not in", values, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdBetween(String value1, String value2) {
            addCriterion("MERCHANT_AD between", value1, value2, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantAdNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_AD not between", value1, value2, "merchantAd");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIsNull() {
            addCriterion("MERCHANT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIsNotNull() {
            addCriterion("MERCHANT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantNameEqualTo(String value) {
            addCriterion("MERCHANT_NAME =", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotEqualTo(String value) {
            addCriterion("MERCHANT_NAME <>", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameGreaterThan(String value) {
            addCriterion("MERCHANT_NAME >", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NAME >=", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLessThan(String value) {
            addCriterion("MERCHANT_NAME <", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NAME <=", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLike(String value) {
            addCriterion("MERCHANT_NAME like", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotLike(String value) {
            addCriterion("MERCHANT_NAME not like", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIn(List<String> values) {
            addCriterion("MERCHANT_NAME in", values, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotIn(List<String> values) {
            addCriterion("MERCHANT_NAME not in", values, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameBetween(String value1, String value2) {
            addCriterion("MERCHANT_NAME between", value1, value2, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_NAME not between", value1, value2, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeIsNull() {
            addCriterion("MERCHANT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeIsNotNull() {
            addCriterion("MERCHANT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeEqualTo(String value) {
            addCriterion("MERCHANT_TYPE =", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNotEqualTo(String value) {
            addCriterion("MERCHANT_TYPE <>", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeGreaterThan(String value) {
            addCriterion("MERCHANT_TYPE >", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_TYPE >=", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeLessThan(String value) {
            addCriterion("MERCHANT_TYPE <", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_TYPE <=", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeLike(String value) {
            addCriterion("MERCHANT_TYPE like", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNotLike(String value) {
            addCriterion("MERCHANT_TYPE not like", value, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeIn(List<String> values) {
            addCriterion("MERCHANT_TYPE in", values, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNotIn(List<String> values) {
            addCriterion("MERCHANT_TYPE not in", values, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeBetween(String value1, String value2) {
            addCriterion("MERCHANT_TYPE between", value1, value2, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantTypeNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_TYPE not between", value1, value2, "merchantType");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressIsNull() {
            addCriterion("MERCHANT_GPS_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressIsNotNull() {
            addCriterion("MERCHANT_GPS_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressEqualTo(String value) {
            addCriterion("MERCHANT_GPS_ADDRESS =", value, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressNotEqualTo(String value) {
            addCriterion("MERCHANT_GPS_ADDRESS <>", value, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressGreaterThan(String value) {
            addCriterion("MERCHANT_GPS_ADDRESS >", value, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_GPS_ADDRESS >=", value, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressLessThan(String value) {
            addCriterion("MERCHANT_GPS_ADDRESS <", value, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_GPS_ADDRESS <=", value, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressLike(String value) {
            addCriterion("MERCHANT_GPS_ADDRESS like", value, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressNotLike(String value) {
            addCriterion("MERCHANT_GPS_ADDRESS not like", value, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressIn(List<String> values) {
            addCriterion("MERCHANT_GPS_ADDRESS in", values, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressNotIn(List<String> values) {
            addCriterion("MERCHANT_GPS_ADDRESS not in", values, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressBetween(String value1, String value2) {
            addCriterion("MERCHANT_GPS_ADDRESS between", value1, value2, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantGpsAddressNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_GPS_ADDRESS not between", value1, value2, "merchantGpsAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantLogIsNull() {
            addCriterion("MERCHANT_LOG is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLogIsNotNull() {
            addCriterion("MERCHANT_LOG is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLogEqualTo(String value) {
            addCriterion("MERCHANT_LOG =", value, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogNotEqualTo(String value) {
            addCriterion("MERCHANT_LOG <>", value, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogGreaterThan(String value) {
            addCriterion("MERCHANT_LOG >", value, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_LOG >=", value, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogLessThan(String value) {
            addCriterion("MERCHANT_LOG <", value, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_LOG <=", value, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogLike(String value) {
            addCriterion("MERCHANT_LOG like", value, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogNotLike(String value) {
            addCriterion("MERCHANT_LOG not like", value, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogIn(List<String> values) {
            addCriterion("MERCHANT_LOG in", values, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogNotIn(List<String> values) {
            addCriterion("MERCHANT_LOG not in", values, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogBetween(String value1, String value2) {
            addCriterion("MERCHANT_LOG between", value1, value2, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLogNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_LOG not between", value1, value2, "merchantLog");
            return (Criteria) this;
        }

        public Criteria andMerchantLatIsNull() {
            addCriterion("MERCHANT_LAT is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLatIsNotNull() {
            addCriterion("MERCHANT_LAT is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLatEqualTo(String value) {
            addCriterion("MERCHANT_LAT =", value, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatNotEqualTo(String value) {
            addCriterion("MERCHANT_LAT <>", value, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatGreaterThan(String value) {
            addCriterion("MERCHANT_LAT >", value, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_LAT >=", value, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatLessThan(String value) {
            addCriterion("MERCHANT_LAT <", value, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_LAT <=", value, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatLike(String value) {
            addCriterion("MERCHANT_LAT like", value, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatNotLike(String value) {
            addCriterion("MERCHANT_LAT not like", value, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatIn(List<String> values) {
            addCriterion("MERCHANT_LAT in", values, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatNotIn(List<String> values) {
            addCriterion("MERCHANT_LAT not in", values, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatBetween(String value1, String value2) {
            addCriterion("MERCHANT_LAT between", value1, value2, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantLatNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_LAT not between", value1, value2, "merchantLat");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroIsNull() {
            addCriterion("MERCHANT_INTRO is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroIsNotNull() {
            addCriterion("MERCHANT_INTRO is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroEqualTo(String value) {
            addCriterion("MERCHANT_INTRO =", value, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroNotEqualTo(String value) {
            addCriterion("MERCHANT_INTRO <>", value, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroGreaterThan(String value) {
            addCriterion("MERCHANT_INTRO >", value, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_INTRO >=", value, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroLessThan(String value) {
            addCriterion("MERCHANT_INTRO <", value, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_INTRO <=", value, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroLike(String value) {
            addCriterion("MERCHANT_INTRO like", value, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroNotLike(String value) {
            addCriterion("MERCHANT_INTRO not like", value, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroIn(List<String> values) {
            addCriterion("MERCHANT_INTRO in", values, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroNotIn(List<String> values) {
            addCriterion("MERCHANT_INTRO not in", values, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroBetween(String value1, String value2) {
            addCriterion("MERCHANT_INTRO between", value1, value2, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantIntroNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_INTRO not between", value1, value2, "merchantIntro");
            return (Criteria) this;
        }

        public Criteria andMerchantStateIsNull() {
            addCriterion("MERCHANT_STATE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantStateIsNotNull() {
            addCriterion("MERCHANT_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantStateEqualTo(Integer value) {
            addCriterion("MERCHANT_STATE =", value, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateNotEqualTo(Integer value) {
            addCriterion("MERCHANT_STATE <>", value, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateGreaterThan(Integer value) {
            addCriterion("MERCHANT_STATE >", value, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("MERCHANT_STATE >=", value, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateLessThan(Integer value) {
            addCriterion("MERCHANT_STATE <", value, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateLessThanOrEqualTo(Integer value) {
            addCriterion("MERCHANT_STATE <=", value, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateIn(List<Integer> values) {
            addCriterion("MERCHANT_STATE in", values, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateNotIn(List<Integer> values) {
            addCriterion("MERCHANT_STATE not in", values, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateBetween(Integer value1, Integer value2) {
            addCriterion("MERCHANT_STATE between", value1, value2, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantStateNotBetween(Integer value1, Integer value2) {
            addCriterion("MERCHANT_STATE not between", value1, value2, "merchantState");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeIsNull() {
            addCriterion("MERCHANT_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeIsNotNull() {
            addCriterion("MERCHANT_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeEqualTo(Date value) {
            addCriterion("MERCHANT_CREATE_TIME =", value, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeNotEqualTo(Date value) {
            addCriterion("MERCHANT_CREATE_TIME <>", value, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeGreaterThan(Date value) {
            addCriterion("MERCHANT_CREATE_TIME >", value, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MERCHANT_CREATE_TIME >=", value, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeLessThan(Date value) {
            addCriterion("MERCHANT_CREATE_TIME <", value, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("MERCHANT_CREATE_TIME <=", value, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeIn(List<Date> values) {
            addCriterion("MERCHANT_CREATE_TIME in", values, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeNotIn(List<Date> values) {
            addCriterion("MERCHANT_CREATE_TIME not in", values, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeBetween(Date value1, Date value2) {
            addCriterion("MERCHANT_CREATE_TIME between", value1, value2, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("MERCHANT_CREATE_TIME not between", value1, value2, "merchantCreateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeIsNull() {
            addCriterion("MERCHANT_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeIsNotNull() {
            addCriterion("MERCHANT_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeEqualTo(Date value) {
            addCriterion("MERCHANT_UPDATE_TIME =", value, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeNotEqualTo(Date value) {
            addCriterion("MERCHANT_UPDATE_TIME <>", value, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeGreaterThan(Date value) {
            addCriterion("MERCHANT_UPDATE_TIME >", value, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MERCHANT_UPDATE_TIME >=", value, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeLessThan(Date value) {
            addCriterion("MERCHANT_UPDATE_TIME <", value, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("MERCHANT_UPDATE_TIME <=", value, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeIn(List<Date> values) {
            addCriterion("MERCHANT_UPDATE_TIME in", values, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeNotIn(List<Date> values) {
            addCriterion("MERCHANT_UPDATE_TIME not in", values, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("MERCHANT_UPDATE_TIME between", value1, value2, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("MERCHANT_UPDATE_TIME not between", value1, value2, "merchantUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMerchantTagIsNull() {
            addCriterion("MERCHANT_TAG is null");
            return (Criteria) this;
        }

        public Criteria andMerchantTagIsNotNull() {
            addCriterion("MERCHANT_TAG is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantTagEqualTo(String value) {
            addCriterion("MERCHANT_TAG =", value, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagNotEqualTo(String value) {
            addCriterion("MERCHANT_TAG <>", value, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagGreaterThan(String value) {
            addCriterion("MERCHANT_TAG >", value, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_TAG >=", value, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagLessThan(String value) {
            addCriterion("MERCHANT_TAG <", value, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_TAG <=", value, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagLike(String value) {
            addCriterion("MERCHANT_TAG like", value, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagNotLike(String value) {
            addCriterion("MERCHANT_TAG not like", value, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagIn(List<String> values) {
            addCriterion("MERCHANT_TAG in", values, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagNotIn(List<String> values) {
            addCriterion("MERCHANT_TAG not in", values, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagBetween(String value1, String value2) {
            addCriterion("MERCHANT_TAG between", value1, value2, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantTagNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_TAG not between", value1, value2, "merchantTag");
            return (Criteria) this;
        }

        public Criteria andMerchantSortIsNull() {
            addCriterion("MERCHANT_SORT is null");
            return (Criteria) this;
        }

        public Criteria andMerchantSortIsNotNull() {
            addCriterion("MERCHANT_SORT is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantSortEqualTo(Integer value) {
            addCriterion("MERCHANT_SORT =", value, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortNotEqualTo(Integer value) {
            addCriterion("MERCHANT_SORT <>", value, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortGreaterThan(Integer value) {
            addCriterion("MERCHANT_SORT >", value, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("MERCHANT_SORT >=", value, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortLessThan(Integer value) {
            addCriterion("MERCHANT_SORT <", value, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortLessThanOrEqualTo(Integer value) {
            addCriterion("MERCHANT_SORT <=", value, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortIn(List<Integer> values) {
            addCriterion("MERCHANT_SORT in", values, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortNotIn(List<Integer> values) {
            addCriterion("MERCHANT_SORT not in", values, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortBetween(Integer value1, Integer value2) {
            addCriterion("MERCHANT_SORT between", value1, value2, "merchantSort");
            return (Criteria) this;
        }

        public Criteria andMerchantSortNotBetween(Integer value1, Integer value2) {
            addCriterion("MERCHANT_SORT not between", value1, value2, "merchantSort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}