package com.cqq.leisure.entity;

import java.util.Date;

public class ProgramPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer programPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer holidayPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String programPlanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String programPlanIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String programPlanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date programPlanStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date programPlanEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String programPlanAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String programPlanMainContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer programPlanSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer programPlanState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date programPlanCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_plan.PROGRAM_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date programPlanUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_ID
     *
     * @return the value of program_plan.PROGRAM_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getProgramPlanId() {
        return programPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_ID
     *
     * @param programPlanId the value for program_plan.PROGRAM_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanId(Integer programPlanId) {
        this.programPlanId = programPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.HOLIDAY_PLAN_ID
     *
     * @return the value of program_plan.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getHolidayPlanId() {
        return holidayPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.HOLIDAY_PLAN_ID
     *
     * @param holidayPlanId the value for program_plan.HOLIDAY_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setHolidayPlanId(Integer holidayPlanId) {
        this.holidayPlanId = holidayPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_NAME
     *
     * @return the value of program_plan.PROGRAM_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getProgramPlanName() {
        return programPlanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_NAME
     *
     * @param programPlanName the value for program_plan.PROGRAM_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanName(String programPlanName) {
        this.programPlanName = programPlanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_ICON_URL
     *
     * @return the value of program_plan.PROGRAM_PLAN_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getProgramPlanIconUrl() {
        return programPlanIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_ICON_URL
     *
     * @param programPlanIconUrl the value for program_plan.PROGRAM_PLAN_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanIconUrl(String programPlanIconUrl) {
        this.programPlanIconUrl = programPlanIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_TYPE
     *
     * @return the value of program_plan.PROGRAM_PLAN_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getProgramPlanType() {
        return programPlanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_TYPE
     *
     * @param programPlanType the value for program_plan.PROGRAM_PLAN_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanType(String programPlanType) {
        this.programPlanType = programPlanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_START_TIME
     *
     * @return the value of program_plan.PROGRAM_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getProgramPlanStartTime() {
        return programPlanStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_START_TIME
     *
     * @param programPlanStartTime the value for program_plan.PROGRAM_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanStartTime(Date programPlanStartTime) {
        this.programPlanStartTime = programPlanStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_END_TIME
     *
     * @return the value of program_plan.PROGRAM_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getProgramPlanEndTime() {
        return programPlanEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_END_TIME
     *
     * @param programPlanEndTime the value for program_plan.PROGRAM_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanEndTime(Date programPlanEndTime) {
        this.programPlanEndTime = programPlanEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_ADDRESS
     *
     * @return the value of program_plan.PROGRAM_PLAN_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getProgramPlanAddress() {
        return programPlanAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_ADDRESS
     *
     * @param programPlanAddress the value for program_plan.PROGRAM_PLAN_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanAddress(String programPlanAddress) {
        this.programPlanAddress = programPlanAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_MAIN_CONTENT
     *
     * @return the value of program_plan.PROGRAM_PLAN_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getProgramPlanMainContent() {
        return programPlanMainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_MAIN_CONTENT
     *
     * @param programPlanMainContent the value for program_plan.PROGRAM_PLAN_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanMainContent(String programPlanMainContent) {
        this.programPlanMainContent = programPlanMainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_SORT
     *
     * @return the value of program_plan.PROGRAM_PLAN_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getProgramPlanSort() {
        return programPlanSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_SORT
     *
     * @param programPlanSort the value for program_plan.PROGRAM_PLAN_SORT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanSort(Integer programPlanSort) {
        this.programPlanSort = programPlanSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_STATE
     *
     * @return the value of program_plan.PROGRAM_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getProgramPlanState() {
        return programPlanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_STATE
     *
     * @param programPlanState the value for program_plan.PROGRAM_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanState(Integer programPlanState) {
        this.programPlanState = programPlanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_CREATE_TIME
     *
     * @return the value of program_plan.PROGRAM_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getProgramPlanCreateTime() {
        return programPlanCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_CREATE_TIME
     *
     * @param programPlanCreateTime the value for program_plan.PROGRAM_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanCreateTime(Date programPlanCreateTime) {
        this.programPlanCreateTime = programPlanCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_plan.PROGRAM_PLAN_UPDATE_TIME
     *
     * @return the value of program_plan.PROGRAM_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getProgramPlanUpdateTime() {
        return programPlanUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_plan.PROGRAM_PLAN_UPDATE_TIME
     *
     * @param programPlanUpdateTime the value for program_plan.PROGRAM_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setProgramPlanUpdateTime(Date programPlanUpdateTime) {
        this.programPlanUpdateTime = programPlanUpdateTime;
    }
}