package com.cqq.leisure.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProgramPlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public ProgramPlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProgramPlanIdIsNull() {
            addCriterion("PROGRAM_PLAN_ID is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdIsNotNull() {
            addCriterion("PROGRAM_PLAN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_ID =", value, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdNotEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_ID <>", value, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdGreaterThan(Integer value) {
            addCriterion("PROGRAM_PLAN_ID >", value, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_ID >=", value, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdLessThan(Integer value) {
            addCriterion("PROGRAM_PLAN_ID <", value, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdLessThanOrEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_ID <=", value, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdIn(List<Integer> values) {
            addCriterion("PROGRAM_PLAN_ID in", values, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdNotIn(List<Integer> values) {
            addCriterion("PROGRAM_PLAN_ID not in", values, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdBetween(Integer value1, Integer value2) {
            addCriterion("PROGRAM_PLAN_ID between", value1, value2, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PROGRAM_PLAN_ID not between", value1, value2, "programPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdIsNull() {
            addCriterion("HOLIDAY_PLAN_ID is null");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdIsNotNull() {
            addCriterion("HOLIDAY_PLAN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdEqualTo(Integer value) {
            addCriterion("HOLIDAY_PLAN_ID =", value, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdNotEqualTo(Integer value) {
            addCriterion("HOLIDAY_PLAN_ID <>", value, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdGreaterThan(Integer value) {
            addCriterion("HOLIDAY_PLAN_ID >", value, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("HOLIDAY_PLAN_ID >=", value, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdLessThan(Integer value) {
            addCriterion("HOLIDAY_PLAN_ID <", value, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdLessThanOrEqualTo(Integer value) {
            addCriterion("HOLIDAY_PLAN_ID <=", value, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdIn(List<Integer> values) {
            addCriterion("HOLIDAY_PLAN_ID in", values, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdNotIn(List<Integer> values) {
            addCriterion("HOLIDAY_PLAN_ID not in", values, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdBetween(Integer value1, Integer value2) {
            addCriterion("HOLIDAY_PLAN_ID between", value1, value2, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andHolidayPlanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("HOLIDAY_PLAN_ID not between", value1, value2, "holidayPlanId");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameIsNull() {
            addCriterion("PROGRAM_PLAN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameIsNotNull() {
            addCriterion("PROGRAM_PLAN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_NAME =", value, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameNotEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_NAME <>", value, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameGreaterThan(String value) {
            addCriterion("PROGRAM_PLAN_NAME >", value, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameGreaterThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_NAME >=", value, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameLessThan(String value) {
            addCriterion("PROGRAM_PLAN_NAME <", value, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameLessThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_NAME <=", value, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameLike(String value) {
            addCriterion("PROGRAM_PLAN_NAME like", value, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameNotLike(String value) {
            addCriterion("PROGRAM_PLAN_NAME not like", value, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_NAME in", values, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameNotIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_NAME not in", values, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_NAME between", value1, value2, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanNameNotBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_NAME not between", value1, value2, "programPlanName");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlIsNull() {
            addCriterion("PROGRAM_PLAN_ICON_URL is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlIsNotNull() {
            addCriterion("PROGRAM_PLAN_ICON_URL is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_ICON_URL =", value, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlNotEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_ICON_URL <>", value, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlGreaterThan(String value) {
            addCriterion("PROGRAM_PLAN_ICON_URL >", value, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_ICON_URL >=", value, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlLessThan(String value) {
            addCriterion("PROGRAM_PLAN_ICON_URL <", value, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlLessThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_ICON_URL <=", value, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlLike(String value) {
            addCriterion("PROGRAM_PLAN_ICON_URL like", value, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlNotLike(String value) {
            addCriterion("PROGRAM_PLAN_ICON_URL not like", value, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_ICON_URL in", values, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlNotIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_ICON_URL not in", values, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_ICON_URL between", value1, value2, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanIconUrlNotBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_ICON_URL not between", value1, value2, "programPlanIconUrl");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeIsNull() {
            addCriterion("PROGRAM_PLAN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeIsNotNull() {
            addCriterion("PROGRAM_PLAN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_TYPE =", value, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeNotEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_TYPE <>", value, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeGreaterThan(String value) {
            addCriterion("PROGRAM_PLAN_TYPE >", value, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_TYPE >=", value, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeLessThan(String value) {
            addCriterion("PROGRAM_PLAN_TYPE <", value, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeLessThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_TYPE <=", value, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeLike(String value) {
            addCriterion("PROGRAM_PLAN_TYPE like", value, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeNotLike(String value) {
            addCriterion("PROGRAM_PLAN_TYPE not like", value, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_TYPE in", values, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeNotIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_TYPE not in", values, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_TYPE between", value1, value2, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanTypeNotBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_TYPE not between", value1, value2, "programPlanType");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeIsNull() {
            addCriterion("PROGRAM_PLAN_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeIsNotNull() {
            addCriterion("PROGRAM_PLAN_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_START_TIME =", value, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeNotEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_START_TIME <>", value, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeGreaterThan(Date value) {
            addCriterion("PROGRAM_PLAN_START_TIME >", value, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_START_TIME >=", value, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeLessThan(Date value) {
            addCriterion("PROGRAM_PLAN_START_TIME <", value, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_START_TIME <=", value, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeIn(List<Date> values) {
            addCriterion("PROGRAM_PLAN_START_TIME in", values, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeNotIn(List<Date> values) {
            addCriterion("PROGRAM_PLAN_START_TIME not in", values, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeBetween(Date value1, Date value2) {
            addCriterion("PROGRAM_PLAN_START_TIME between", value1, value2, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("PROGRAM_PLAN_START_TIME not between", value1, value2, "programPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeIsNull() {
            addCriterion("PROGRAM_PLAN_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeIsNotNull() {
            addCriterion("PROGRAM_PLAN_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_END_TIME =", value, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeNotEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_END_TIME <>", value, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeGreaterThan(Date value) {
            addCriterion("PROGRAM_PLAN_END_TIME >", value, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_END_TIME >=", value, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeLessThan(Date value) {
            addCriterion("PROGRAM_PLAN_END_TIME <", value, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_END_TIME <=", value, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeIn(List<Date> values) {
            addCriterion("PROGRAM_PLAN_END_TIME in", values, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeNotIn(List<Date> values) {
            addCriterion("PROGRAM_PLAN_END_TIME not in", values, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeBetween(Date value1, Date value2) {
            addCriterion("PROGRAM_PLAN_END_TIME between", value1, value2, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("PROGRAM_PLAN_END_TIME not between", value1, value2, "programPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressIsNull() {
            addCriterion("PROGRAM_PLAN_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressIsNotNull() {
            addCriterion("PROGRAM_PLAN_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_ADDRESS =", value, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressNotEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_ADDRESS <>", value, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressGreaterThan(String value) {
            addCriterion("PROGRAM_PLAN_ADDRESS >", value, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressGreaterThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_ADDRESS >=", value, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressLessThan(String value) {
            addCriterion("PROGRAM_PLAN_ADDRESS <", value, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressLessThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_ADDRESS <=", value, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressLike(String value) {
            addCriterion("PROGRAM_PLAN_ADDRESS like", value, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressNotLike(String value) {
            addCriterion("PROGRAM_PLAN_ADDRESS not like", value, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_ADDRESS in", values, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressNotIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_ADDRESS not in", values, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_ADDRESS between", value1, value2, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanAddressNotBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_ADDRESS not between", value1, value2, "programPlanAddress");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentIsNull() {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentIsNotNull() {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT =", value, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentNotEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT <>", value, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentGreaterThan(String value) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT >", value, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentGreaterThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT >=", value, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentLessThan(String value) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT <", value, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentLessThanOrEqualTo(String value) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT <=", value, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentLike(String value) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT like", value, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentNotLike(String value) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT not like", value, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT in", values, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentNotIn(List<String> values) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT not in", values, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT between", value1, value2, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanMainContentNotBetween(String value1, String value2) {
            addCriterion("PROGRAM_PLAN_MAIN_CONTENT not between", value1, value2, "programPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortIsNull() {
            addCriterion("PROGRAM_PLAN_SORT is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortIsNotNull() {
            addCriterion("PROGRAM_PLAN_SORT is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_SORT =", value, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortNotEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_SORT <>", value, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortGreaterThan(Integer value) {
            addCriterion("PROGRAM_PLAN_SORT >", value, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_SORT >=", value, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortLessThan(Integer value) {
            addCriterion("PROGRAM_PLAN_SORT <", value, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortLessThanOrEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_SORT <=", value, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortIn(List<Integer> values) {
            addCriterion("PROGRAM_PLAN_SORT in", values, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortNotIn(List<Integer> values) {
            addCriterion("PROGRAM_PLAN_SORT not in", values, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortBetween(Integer value1, Integer value2) {
            addCriterion("PROGRAM_PLAN_SORT between", value1, value2, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanSortNotBetween(Integer value1, Integer value2) {
            addCriterion("PROGRAM_PLAN_SORT not between", value1, value2, "programPlanSort");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateIsNull() {
            addCriterion("PROGRAM_PLAN_STATE is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateIsNotNull() {
            addCriterion("PROGRAM_PLAN_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_STATE =", value, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateNotEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_STATE <>", value, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateGreaterThan(Integer value) {
            addCriterion("PROGRAM_PLAN_STATE >", value, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_STATE >=", value, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateLessThan(Integer value) {
            addCriterion("PROGRAM_PLAN_STATE <", value, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateLessThanOrEqualTo(Integer value) {
            addCriterion("PROGRAM_PLAN_STATE <=", value, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateIn(List<Integer> values) {
            addCriterion("PROGRAM_PLAN_STATE in", values, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateNotIn(List<Integer> values) {
            addCriterion("PROGRAM_PLAN_STATE not in", values, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateBetween(Integer value1, Integer value2) {
            addCriterion("PROGRAM_PLAN_STATE between", value1, value2, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanStateNotBetween(Integer value1, Integer value2) {
            addCriterion("PROGRAM_PLAN_STATE not between", value1, value2, "programPlanState");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeIsNull() {
            addCriterion("PROGRAM_PLAN_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeIsNotNull() {
            addCriterion("PROGRAM_PLAN_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME =", value, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeNotEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME <>", value, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeGreaterThan(Date value) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME >", value, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME >=", value, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeLessThan(Date value) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME <", value, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME <=", value, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeIn(List<Date> values) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME in", values, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeNotIn(List<Date> values) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME not in", values, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeBetween(Date value1, Date value2) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME between", value1, value2, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("PROGRAM_PLAN_CREATE_TIME not between", value1, value2, "programPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeIsNull() {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeIsNotNull() {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME =", value, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeNotEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME <>", value, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeGreaterThan(Date value) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME >", value, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME >=", value, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeLessThan(Date value) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME <", value, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME <=", value, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeIn(List<Date> values) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME in", values, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeNotIn(List<Date> values) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME not in", values, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME between", value1, value2, "programPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andProgramPlanUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("PROGRAM_PLAN_UPDATE_TIME not between", value1, value2, "programPlanUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table program_plan
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table program_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}