package com.cqq.leisure.entity;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.TAG_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.TAG_IMG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String tagImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.TAG_ID
     *
     * @return the value of tag.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.TAG_ID
     *
     * @param tagId the value for tag.TAG_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.TAG_NAME
     *
     * @return the value of tag.TAG_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.TAG_NAME
     *
     * @param tagName the value for tag.TAG_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.TAG_IMG
     *
     * @return the value of tag.TAG_IMG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getTagImg() {
        return tagImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.TAG_IMG
     *
     * @param tagImg the value for tag.TAG_IMG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setTagImg(String tagImg) {
        this.tagImg = tagImg;
    }
}