package com.cqq.leisure.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserPlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public UserPlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserPlanIdIsNull() {
            addCriterion("USER_PLAN_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdIsNotNull() {
            addCriterion("USER_PLAN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdEqualTo(Integer value) {
            addCriterion("USER_PLAN_ID =", value, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdNotEqualTo(Integer value) {
            addCriterion("USER_PLAN_ID <>", value, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdGreaterThan(Integer value) {
            addCriterion("USER_PLAN_ID >", value, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_PLAN_ID >=", value, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdLessThan(Integer value) {
            addCriterion("USER_PLAN_ID <", value, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_PLAN_ID <=", value, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdIn(List<Integer> values) {
            addCriterion("USER_PLAN_ID in", values, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdNotIn(List<Integer> values) {
            addCriterion("USER_PLAN_ID not in", values, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_PLAN_ID between", value1, value2, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserPlanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_PLAN_ID not between", value1, value2, "userPlanId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameIsNull() {
            addCriterion("USER_PLAN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameIsNotNull() {
            addCriterion("USER_PLAN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameEqualTo(String value) {
            addCriterion("USER_PLAN_NAME =", value, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameNotEqualTo(String value) {
            addCriterion("USER_PLAN_NAME <>", value, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameGreaterThan(String value) {
            addCriterion("USER_PLAN_NAME >", value, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_PLAN_NAME >=", value, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameLessThan(String value) {
            addCriterion("USER_PLAN_NAME <", value, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameLessThanOrEqualTo(String value) {
            addCriterion("USER_PLAN_NAME <=", value, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameLike(String value) {
            addCriterion("USER_PLAN_NAME like", value, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameNotLike(String value) {
            addCriterion("USER_PLAN_NAME not like", value, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameIn(List<String> values) {
            addCriterion("USER_PLAN_NAME in", values, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameNotIn(List<String> values) {
            addCriterion("USER_PLAN_NAME not in", values, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameBetween(String value1, String value2) {
            addCriterion("USER_PLAN_NAME between", value1, value2, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanNameNotBetween(String value1, String value2) {
            addCriterion("USER_PLAN_NAME not between", value1, value2, "userPlanName");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentIsNull() {
            addCriterion("USER_PLAN_MAIN_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentIsNotNull() {
            addCriterion("USER_PLAN_MAIN_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentEqualTo(String value) {
            addCriterion("USER_PLAN_MAIN_CONTENT =", value, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentNotEqualTo(String value) {
            addCriterion("USER_PLAN_MAIN_CONTENT <>", value, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentGreaterThan(String value) {
            addCriterion("USER_PLAN_MAIN_CONTENT >", value, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentGreaterThanOrEqualTo(String value) {
            addCriterion("USER_PLAN_MAIN_CONTENT >=", value, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentLessThan(String value) {
            addCriterion("USER_PLAN_MAIN_CONTENT <", value, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentLessThanOrEqualTo(String value) {
            addCriterion("USER_PLAN_MAIN_CONTENT <=", value, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentLike(String value) {
            addCriterion("USER_PLAN_MAIN_CONTENT like", value, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentNotLike(String value) {
            addCriterion("USER_PLAN_MAIN_CONTENT not like", value, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentIn(List<String> values) {
            addCriterion("USER_PLAN_MAIN_CONTENT in", values, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentNotIn(List<String> values) {
            addCriterion("USER_PLAN_MAIN_CONTENT not in", values, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentBetween(String value1, String value2) {
            addCriterion("USER_PLAN_MAIN_CONTENT between", value1, value2, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanMainContentNotBetween(String value1, String value2) {
            addCriterion("USER_PLAN_MAIN_CONTENT not between", value1, value2, "userPlanMainContent");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeIsNull() {
            addCriterion("USER_PLAN_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeIsNotNull() {
            addCriterion("USER_PLAN_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeEqualTo(Date value) {
            addCriterion("USER_PLAN_START_TIME =", value, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeNotEqualTo(Date value) {
            addCriterion("USER_PLAN_START_TIME <>", value, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeGreaterThan(Date value) {
            addCriterion("USER_PLAN_START_TIME >", value, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_PLAN_START_TIME >=", value, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeLessThan(Date value) {
            addCriterion("USER_PLAN_START_TIME <", value, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("USER_PLAN_START_TIME <=", value, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeIn(List<Date> values) {
            addCriterion("USER_PLAN_START_TIME in", values, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeNotIn(List<Date> values) {
            addCriterion("USER_PLAN_START_TIME not in", values, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeBetween(Date value1, Date value2) {
            addCriterion("USER_PLAN_START_TIME between", value1, value2, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("USER_PLAN_START_TIME not between", value1, value2, "userPlanStartTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeIsNull() {
            addCriterion("USER_PLAN_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeIsNotNull() {
            addCriterion("USER_PLAN_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeEqualTo(Date value) {
            addCriterion("USER_PLAN_END_TIME =", value, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeNotEqualTo(Date value) {
            addCriterion("USER_PLAN_END_TIME <>", value, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeGreaterThan(Date value) {
            addCriterion("USER_PLAN_END_TIME >", value, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_PLAN_END_TIME >=", value, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeLessThan(Date value) {
            addCriterion("USER_PLAN_END_TIME <", value, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("USER_PLAN_END_TIME <=", value, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeIn(List<Date> values) {
            addCriterion("USER_PLAN_END_TIME in", values, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeNotIn(List<Date> values) {
            addCriterion("USER_PLAN_END_TIME not in", values, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeBetween(Date value1, Date value2) {
            addCriterion("USER_PLAN_END_TIME between", value1, value2, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("USER_PLAN_END_TIME not between", value1, value2, "userPlanEndTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateIsNull() {
            addCriterion("USER_PLAN_STATE is null");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateIsNotNull() {
            addCriterion("USER_PLAN_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateEqualTo(Integer value) {
            addCriterion("USER_PLAN_STATE =", value, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateNotEqualTo(Integer value) {
            addCriterion("USER_PLAN_STATE <>", value, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateGreaterThan(Integer value) {
            addCriterion("USER_PLAN_STATE >", value, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_PLAN_STATE >=", value, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateLessThan(Integer value) {
            addCriterion("USER_PLAN_STATE <", value, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateLessThanOrEqualTo(Integer value) {
            addCriterion("USER_PLAN_STATE <=", value, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateIn(List<Integer> values) {
            addCriterion("USER_PLAN_STATE in", values, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateNotIn(List<Integer> values) {
            addCriterion("USER_PLAN_STATE not in", values, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateBetween(Integer value1, Integer value2) {
            addCriterion("USER_PLAN_STATE between", value1, value2, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanStateNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_PLAN_STATE not between", value1, value2, "userPlanState");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeIsNull() {
            addCriterion("USER_PLAN_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeIsNotNull() {
            addCriterion("USER_PLAN_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeEqualTo(Date value) {
            addCriterion("USER_PLAN_CREATE_TIME =", value, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeNotEqualTo(Date value) {
            addCriterion("USER_PLAN_CREATE_TIME <>", value, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeGreaterThan(Date value) {
            addCriterion("USER_PLAN_CREATE_TIME >", value, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_PLAN_CREATE_TIME >=", value, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeLessThan(Date value) {
            addCriterion("USER_PLAN_CREATE_TIME <", value, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("USER_PLAN_CREATE_TIME <=", value, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeIn(List<Date> values) {
            addCriterion("USER_PLAN_CREATE_TIME in", values, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeNotIn(List<Date> values) {
            addCriterion("USER_PLAN_CREATE_TIME not in", values, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeBetween(Date value1, Date value2) {
            addCriterion("USER_PLAN_CREATE_TIME between", value1, value2, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("USER_PLAN_CREATE_TIME not between", value1, value2, "userPlanCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeIsNull() {
            addCriterion("USER_PLAN_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeIsNotNull() {
            addCriterion("USER_PLAN_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeEqualTo(Date value) {
            addCriterion("USER_PLAN_UPDATE_TIME =", value, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeNotEqualTo(Date value) {
            addCriterion("USER_PLAN_UPDATE_TIME <>", value, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeGreaterThan(Date value) {
            addCriterion("USER_PLAN_UPDATE_TIME >", value, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_PLAN_UPDATE_TIME >=", value, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeLessThan(Date value) {
            addCriterion("USER_PLAN_UPDATE_TIME <", value, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("USER_PLAN_UPDATE_TIME <=", value, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeIn(List<Date> values) {
            addCriterion("USER_PLAN_UPDATE_TIME in", values, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeNotIn(List<Date> values) {
            addCriterion("USER_PLAN_UPDATE_TIME not in", values, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("USER_PLAN_UPDATE_TIME between", value1, value2, "userPlanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserPlanUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("USER_PLAN_UPDATE_TIME not between", value1, value2, "userPlanUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_plan
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_plan
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}