package com.cqq.leisure.entity;

import java.util.Date;

public class UserPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer userPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userPlanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_PLAN_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userPlanMainContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date userPlanStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date userPlanEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer userPlanState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date userPlanCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_plan.USER_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date userPlanUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_PLAN_ID
     *
     * @return the value of user_plan.USER_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getUserPlanId() {
        return userPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_PLAN_ID
     *
     * @param userPlanId the value for user_plan.USER_PLAN_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPlanId(Integer userPlanId) {
        this.userPlanId = userPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_ID
     *
     * @return the value of user_plan.USER_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_ID
     *
     * @param userId the value for user_plan.USER_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_PLAN_NAME
     *
     * @return the value of user_plan.USER_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserPlanName() {
        return userPlanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_PLAN_NAME
     *
     * @param userPlanName the value for user_plan.USER_PLAN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPlanName(String userPlanName) {
        this.userPlanName = userPlanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_PLAN_MAIN_CONTENT
     *
     * @return the value of user_plan.USER_PLAN_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserPlanMainContent() {
        return userPlanMainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_PLAN_MAIN_CONTENT
     *
     * @param userPlanMainContent the value for user_plan.USER_PLAN_MAIN_CONTENT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPlanMainContent(String userPlanMainContent) {
        this.userPlanMainContent = userPlanMainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_PLAN_START_TIME
     *
     * @return the value of user_plan.USER_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getUserPlanStartTime() {
        return userPlanStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_PLAN_START_TIME
     *
     * @param userPlanStartTime the value for user_plan.USER_PLAN_START_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPlanStartTime(Date userPlanStartTime) {
        this.userPlanStartTime = userPlanStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_PLAN_END_TIME
     *
     * @return the value of user_plan.USER_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getUserPlanEndTime() {
        return userPlanEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_PLAN_END_TIME
     *
     * @param userPlanEndTime the value for user_plan.USER_PLAN_END_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPlanEndTime(Date userPlanEndTime) {
        this.userPlanEndTime = userPlanEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_PLAN_STATE
     *
     * @return the value of user_plan.USER_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getUserPlanState() {
        return userPlanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_PLAN_STATE
     *
     * @param userPlanState the value for user_plan.USER_PLAN_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPlanState(Integer userPlanState) {
        this.userPlanState = userPlanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_PLAN_CREATE_TIME
     *
     * @return the value of user_plan.USER_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getUserPlanCreateTime() {
        return userPlanCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_PLAN_CREATE_TIME
     *
     * @param userPlanCreateTime the value for user_plan.USER_PLAN_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPlanCreateTime(Date userPlanCreateTime) {
        this.userPlanCreateTime = userPlanCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_plan.USER_PLAN_UPDATE_TIME
     *
     * @return the value of user_plan.USER_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getUserPlanUpdateTime() {
        return userPlanUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_plan.USER_PLAN_UPDATE_TIME
     *
     * @param userPlanUpdateTime the value for user_plan.USER_PLAN_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPlanUpdateTime(Date userPlanUpdateTime) {
        this.userPlanUpdateTime = userPlanUpdateTime;
    }
}