package com.cqq.leisure.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_LOGIN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userLoginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_REL_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userRelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_PASSWORD
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_HOBBY
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userHobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_MAIN_RANGE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userMainRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ACTIVE_RANGE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userActiveRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_TELE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userTele;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_EMAIL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_GPS_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userGpsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private String userLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date userCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    private Date userUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ID
     *
     * @return the value of user.USER_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ID
     *
     * @param userId the value for user.USER_ID
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ICON_URL
     *
     * @return the value of user.USER_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserIconUrl() {
        return userIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ICON_URL
     *
     * @param userIconUrl the value for user.USER_ICON_URL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserIconUrl(String userIconUrl) {
        this.userIconUrl = userIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_LOGIN_NAME
     *
     * @return the value of user.USER_LOGIN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserLoginName() {
        return userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_LOGIN_NAME
     *
     * @param userLoginName the value for user.USER_LOGIN_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserLoginName(String userLoginName) {
        this.userLoginName = userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_REL_NAME
     *
     * @return the value of user.USER_REL_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserRelName() {
        return userRelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_REL_NAME
     *
     * @param userRelName the value for user.USER_REL_NAME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserRelName(String userRelName) {
        this.userRelName = userRelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_PASSWORD
     *
     * @return the value of user.USER_PASSWORD
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_PASSWORD
     *
     * @param userPassword the value for user.USER_PASSWORD
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_HOBBY
     *
     * @return the value of user.USER_HOBBY
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserHobby() {
        return userHobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_HOBBY
     *
     * @param userHobby the value for user.USER_HOBBY
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserHobby(String userHobby) {
        this.userHobby = userHobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_MAIN_RANGE
     *
     * @return the value of user.USER_MAIN_RANGE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserMainRange() {
        return userMainRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_MAIN_RANGE
     *
     * @param userMainRange the value for user.USER_MAIN_RANGE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserMainRange(String userMainRange) {
        this.userMainRange = userMainRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ACTIVE_RANGE
     *
     * @return the value of user.USER_ACTIVE_RANGE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserActiveRange() {
        return userActiveRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ACTIVE_RANGE
     *
     * @param userActiveRange the value for user.USER_ACTIVE_RANGE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserActiveRange(String userActiveRange) {
        this.userActiveRange = userActiveRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_TYPE
     *
     * @return the value of user.USER_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_TYPE
     *
     * @param userType the value for user.USER_TYPE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_STATE
     *
     * @return the value of user.USER_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_STATE
     *
     * @param userState the value for user.USER_STATE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_TELE
     *
     * @return the value of user.USER_TELE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserTele() {
        return userTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_TELE
     *
     * @param userTele the value for user.USER_TELE
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserTele(String userTele) {
        this.userTele = userTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_EMAIL
     *
     * @return the value of user.USER_EMAIL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_EMAIL
     *
     * @param userEmail the value for user.USER_EMAIL
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_GPS_ADDRESS
     *
     * @return the value of user.USER_GPS_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserGpsAddress() {
        return userGpsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_GPS_ADDRESS
     *
     * @param userGpsAddress the value for user.USER_GPS_ADDRESS
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserGpsAddress(String userGpsAddress) {
        this.userGpsAddress = userGpsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_LOG
     *
     * @return the value of user.USER_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserLog() {
        return userLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_LOG
     *
     * @param userLog the value for user.USER_LOG
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserLog(String userLog) {
        this.userLog = userLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_LAT
     *
     * @return the value of user.USER_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getUserLat() {
        return userLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_LAT
     *
     * @param userLat the value for user.USER_LAT
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserLat(String userLat) {
        this.userLat = userLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_CREATE_TIME
     *
     * @return the value of user.USER_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_CREATE_TIME
     *
     * @param userCreateTime the value for user.USER_CREATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_UPDATE_TIME
     *
     * @return the value of user.USER_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Date getUserUpdateTime() {
        return userUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_UPDATE_TIME
     *
     * @param userUpdateTime the value for user.USER_UPDATE_TIME
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setUserUpdateTime(Date userUpdateTime) {
        this.userUpdateTime = userUpdateTime;
    }
}