package com.cqq.leisure.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlIsNull() {
            addCriterion("USER_ICON_URL is null");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlIsNotNull() {
            addCriterion("USER_ICON_URL is not null");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlEqualTo(String value) {
            addCriterion("USER_ICON_URL =", value, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlNotEqualTo(String value) {
            addCriterion("USER_ICON_URL <>", value, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlGreaterThan(String value) {
            addCriterion("USER_ICON_URL >", value, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ICON_URL >=", value, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlLessThan(String value) {
            addCriterion("USER_ICON_URL <", value, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlLessThanOrEqualTo(String value) {
            addCriterion("USER_ICON_URL <=", value, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlLike(String value) {
            addCriterion("USER_ICON_URL like", value, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlNotLike(String value) {
            addCriterion("USER_ICON_URL not like", value, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlIn(List<String> values) {
            addCriterion("USER_ICON_URL in", values, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlNotIn(List<String> values) {
            addCriterion("USER_ICON_URL not in", values, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlBetween(String value1, String value2) {
            addCriterion("USER_ICON_URL between", value1, value2, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserIconUrlNotBetween(String value1, String value2) {
            addCriterion("USER_ICON_URL not between", value1, value2, "userIconUrl");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameIsNull() {
            addCriterion("USER_LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameIsNotNull() {
            addCriterion("USER_LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameEqualTo(String value) {
            addCriterion("USER_LOGIN_NAME =", value, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameNotEqualTo(String value) {
            addCriterion("USER_LOGIN_NAME <>", value, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameGreaterThan(String value) {
            addCriterion("USER_LOGIN_NAME >", value, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_LOGIN_NAME >=", value, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameLessThan(String value) {
            addCriterion("USER_LOGIN_NAME <", value, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameLessThanOrEqualTo(String value) {
            addCriterion("USER_LOGIN_NAME <=", value, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameLike(String value) {
            addCriterion("USER_LOGIN_NAME like", value, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameNotLike(String value) {
            addCriterion("USER_LOGIN_NAME not like", value, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameIn(List<String> values) {
            addCriterion("USER_LOGIN_NAME in", values, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameNotIn(List<String> values) {
            addCriterion("USER_LOGIN_NAME not in", values, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameBetween(String value1, String value2) {
            addCriterion("USER_LOGIN_NAME between", value1, value2, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserLoginNameNotBetween(String value1, String value2) {
            addCriterion("USER_LOGIN_NAME not between", value1, value2, "userLoginName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameIsNull() {
            addCriterion("USER_REL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserRelNameIsNotNull() {
            addCriterion("USER_REL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserRelNameEqualTo(String value) {
            addCriterion("USER_REL_NAME =", value, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameNotEqualTo(String value) {
            addCriterion("USER_REL_NAME <>", value, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameGreaterThan(String value) {
            addCriterion("USER_REL_NAME >", value, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_REL_NAME >=", value, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameLessThan(String value) {
            addCriterion("USER_REL_NAME <", value, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameLessThanOrEqualTo(String value) {
            addCriterion("USER_REL_NAME <=", value, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameLike(String value) {
            addCriterion("USER_REL_NAME like", value, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameNotLike(String value) {
            addCriterion("USER_REL_NAME not like", value, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameIn(List<String> values) {
            addCriterion("USER_REL_NAME in", values, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameNotIn(List<String> values) {
            addCriterion("USER_REL_NAME not in", values, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameBetween(String value1, String value2) {
            addCriterion("USER_REL_NAME between", value1, value2, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserRelNameNotBetween(String value1, String value2) {
            addCriterion("USER_REL_NAME not between", value1, value2, "userRelName");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("USER_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("USER_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("USER_PASSWORD =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("USER_PASSWORD <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("USER_PASSWORD >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("USER_PASSWORD >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("USER_PASSWORD <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("USER_PASSWORD <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("USER_PASSWORD like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("USER_PASSWORD not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("USER_PASSWORD in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("USER_PASSWORD not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("USER_PASSWORD between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("USER_PASSWORD not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserHobbyIsNull() {
            addCriterion("USER_HOBBY is null");
            return (Criteria) this;
        }

        public Criteria andUserHobbyIsNotNull() {
            addCriterion("USER_HOBBY is not null");
            return (Criteria) this;
        }

        public Criteria andUserHobbyEqualTo(String value) {
            addCriterion("USER_HOBBY =", value, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyNotEqualTo(String value) {
            addCriterion("USER_HOBBY <>", value, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyGreaterThan(String value) {
            addCriterion("USER_HOBBY >", value, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyGreaterThanOrEqualTo(String value) {
            addCriterion("USER_HOBBY >=", value, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyLessThan(String value) {
            addCriterion("USER_HOBBY <", value, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyLessThanOrEqualTo(String value) {
            addCriterion("USER_HOBBY <=", value, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyLike(String value) {
            addCriterion("USER_HOBBY like", value, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyNotLike(String value) {
            addCriterion("USER_HOBBY not like", value, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyIn(List<String> values) {
            addCriterion("USER_HOBBY in", values, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyNotIn(List<String> values) {
            addCriterion("USER_HOBBY not in", values, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyBetween(String value1, String value2) {
            addCriterion("USER_HOBBY between", value1, value2, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserHobbyNotBetween(String value1, String value2) {
            addCriterion("USER_HOBBY not between", value1, value2, "userHobby");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeIsNull() {
            addCriterion("USER_MAIN_RANGE is null");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeIsNotNull() {
            addCriterion("USER_MAIN_RANGE is not null");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeEqualTo(String value) {
            addCriterion("USER_MAIN_RANGE =", value, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeNotEqualTo(String value) {
            addCriterion("USER_MAIN_RANGE <>", value, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeGreaterThan(String value) {
            addCriterion("USER_MAIN_RANGE >", value, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_MAIN_RANGE >=", value, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeLessThan(String value) {
            addCriterion("USER_MAIN_RANGE <", value, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeLessThanOrEqualTo(String value) {
            addCriterion("USER_MAIN_RANGE <=", value, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeLike(String value) {
            addCriterion("USER_MAIN_RANGE like", value, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeNotLike(String value) {
            addCriterion("USER_MAIN_RANGE not like", value, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeIn(List<String> values) {
            addCriterion("USER_MAIN_RANGE in", values, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeNotIn(List<String> values) {
            addCriterion("USER_MAIN_RANGE not in", values, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeBetween(String value1, String value2) {
            addCriterion("USER_MAIN_RANGE between", value1, value2, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserMainRangeNotBetween(String value1, String value2) {
            addCriterion("USER_MAIN_RANGE not between", value1, value2, "userMainRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeIsNull() {
            addCriterion("USER_ACTIVE_RANGE is null");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeIsNotNull() {
            addCriterion("USER_ACTIVE_RANGE is not null");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeEqualTo(String value) {
            addCriterion("USER_ACTIVE_RANGE =", value, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeNotEqualTo(String value) {
            addCriterion("USER_ACTIVE_RANGE <>", value, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeGreaterThan(String value) {
            addCriterion("USER_ACTIVE_RANGE >", value, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ACTIVE_RANGE >=", value, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeLessThan(String value) {
            addCriterion("USER_ACTIVE_RANGE <", value, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeLessThanOrEqualTo(String value) {
            addCriterion("USER_ACTIVE_RANGE <=", value, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeLike(String value) {
            addCriterion("USER_ACTIVE_RANGE like", value, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeNotLike(String value) {
            addCriterion("USER_ACTIVE_RANGE not like", value, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeIn(List<String> values) {
            addCriterion("USER_ACTIVE_RANGE in", values, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeNotIn(List<String> values) {
            addCriterion("USER_ACTIVE_RANGE not in", values, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeBetween(String value1, String value2) {
            addCriterion("USER_ACTIVE_RANGE between", value1, value2, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserActiveRangeNotBetween(String value1, String value2) {
            addCriterion("USER_ACTIVE_RANGE not between", value1, value2, "userActiveRange");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("USER_TYPE =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("USER_TYPE <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("USER_TYPE >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TYPE >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("USER_TYPE <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("USER_TYPE <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("USER_TYPE like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("USER_TYPE not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("USER_TYPE in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("USER_TYPE not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("USER_TYPE between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("USER_TYPE not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNull() {
            addCriterion("USER_STATE is null");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNotNull() {
            addCriterion("USER_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andUserStateEqualTo(Integer value) {
            addCriterion("USER_STATE =", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotEqualTo(Integer value) {
            addCriterion("USER_STATE <>", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThan(Integer value) {
            addCriterion("USER_STATE >", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_STATE >=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThan(Integer value) {
            addCriterion("USER_STATE <", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThanOrEqualTo(Integer value) {
            addCriterion("USER_STATE <=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateIn(List<Integer> values) {
            addCriterion("USER_STATE in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotIn(List<Integer> values) {
            addCriterion("USER_STATE not in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateBetween(Integer value1, Integer value2) {
            addCriterion("USER_STATE between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_STATE not between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserTeleIsNull() {
            addCriterion("USER_TELE is null");
            return (Criteria) this;
        }

        public Criteria andUserTeleIsNotNull() {
            addCriterion("USER_TELE is not null");
            return (Criteria) this;
        }

        public Criteria andUserTeleEqualTo(String value) {
            addCriterion("USER_TELE =", value, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleNotEqualTo(String value) {
            addCriterion("USER_TELE <>", value, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleGreaterThan(String value) {
            addCriterion("USER_TELE >", value, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TELE >=", value, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleLessThan(String value) {
            addCriterion("USER_TELE <", value, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleLessThanOrEqualTo(String value) {
            addCriterion("USER_TELE <=", value, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleLike(String value) {
            addCriterion("USER_TELE like", value, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleNotLike(String value) {
            addCriterion("USER_TELE not like", value, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleIn(List<String> values) {
            addCriterion("USER_TELE in", values, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleNotIn(List<String> values) {
            addCriterion("USER_TELE not in", values, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleBetween(String value1, String value2) {
            addCriterion("USER_TELE between", value1, value2, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserTeleNotBetween(String value1, String value2) {
            addCriterion("USER_TELE not between", value1, value2, "userTele");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("USER_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("USER_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("USER_EMAIL =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("USER_EMAIL <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("USER_EMAIL >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("USER_EMAIL <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("USER_EMAIL like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("USER_EMAIL not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("USER_EMAIL in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("USER_EMAIL not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("USER_EMAIL between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("USER_EMAIL not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressIsNull() {
            addCriterion("USER_GPS_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressIsNotNull() {
            addCriterion("USER_GPS_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressEqualTo(String value) {
            addCriterion("USER_GPS_ADDRESS =", value, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressNotEqualTo(String value) {
            addCriterion("USER_GPS_ADDRESS <>", value, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressGreaterThan(String value) {
            addCriterion("USER_GPS_ADDRESS >", value, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressGreaterThanOrEqualTo(String value) {
            addCriterion("USER_GPS_ADDRESS >=", value, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressLessThan(String value) {
            addCriterion("USER_GPS_ADDRESS <", value, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressLessThanOrEqualTo(String value) {
            addCriterion("USER_GPS_ADDRESS <=", value, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressLike(String value) {
            addCriterion("USER_GPS_ADDRESS like", value, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressNotLike(String value) {
            addCriterion("USER_GPS_ADDRESS not like", value, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressIn(List<String> values) {
            addCriterion("USER_GPS_ADDRESS in", values, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressNotIn(List<String> values) {
            addCriterion("USER_GPS_ADDRESS not in", values, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressBetween(String value1, String value2) {
            addCriterion("USER_GPS_ADDRESS between", value1, value2, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserGpsAddressNotBetween(String value1, String value2) {
            addCriterion("USER_GPS_ADDRESS not between", value1, value2, "userGpsAddress");
            return (Criteria) this;
        }

        public Criteria andUserLogIsNull() {
            addCriterion("USER_LOG is null");
            return (Criteria) this;
        }

        public Criteria andUserLogIsNotNull() {
            addCriterion("USER_LOG is not null");
            return (Criteria) this;
        }

        public Criteria andUserLogEqualTo(String value) {
            addCriterion("USER_LOG =", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogNotEqualTo(String value) {
            addCriterion("USER_LOG <>", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogGreaterThan(String value) {
            addCriterion("USER_LOG >", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogGreaterThanOrEqualTo(String value) {
            addCriterion("USER_LOG >=", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogLessThan(String value) {
            addCriterion("USER_LOG <", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogLessThanOrEqualTo(String value) {
            addCriterion("USER_LOG <=", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogLike(String value) {
            addCriterion("USER_LOG like", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogNotLike(String value) {
            addCriterion("USER_LOG not like", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogIn(List<String> values) {
            addCriterion("USER_LOG in", values, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogNotIn(List<String> values) {
            addCriterion("USER_LOG not in", values, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogBetween(String value1, String value2) {
            addCriterion("USER_LOG between", value1, value2, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogNotBetween(String value1, String value2) {
            addCriterion("USER_LOG not between", value1, value2, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLatIsNull() {
            addCriterion("USER_LAT is null");
            return (Criteria) this;
        }

        public Criteria andUserLatIsNotNull() {
            addCriterion("USER_LAT is not null");
            return (Criteria) this;
        }

        public Criteria andUserLatEqualTo(String value) {
            addCriterion("USER_LAT =", value, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatNotEqualTo(String value) {
            addCriterion("USER_LAT <>", value, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatGreaterThan(String value) {
            addCriterion("USER_LAT >", value, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatGreaterThanOrEqualTo(String value) {
            addCriterion("USER_LAT >=", value, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatLessThan(String value) {
            addCriterion("USER_LAT <", value, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatLessThanOrEqualTo(String value) {
            addCriterion("USER_LAT <=", value, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatLike(String value) {
            addCriterion("USER_LAT like", value, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatNotLike(String value) {
            addCriterion("USER_LAT not like", value, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatIn(List<String> values) {
            addCriterion("USER_LAT in", values, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatNotIn(List<String> values) {
            addCriterion("USER_LAT not in", values, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatBetween(String value1, String value2) {
            addCriterion("USER_LAT between", value1, value2, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserLatNotBetween(String value1, String value2) {
            addCriterion("USER_LAT not between", value1, value2, "userLat");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIsNull() {
            addCriterion("USER_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIsNotNull() {
            addCriterion("USER_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeEqualTo(Date value) {
            addCriterion("USER_CREATE_TIME =", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotEqualTo(Date value) {
            addCriterion("USER_CREATE_TIME <>", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeGreaterThan(Date value) {
            addCriterion("USER_CREATE_TIME >", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_CREATE_TIME >=", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeLessThan(Date value) {
            addCriterion("USER_CREATE_TIME <", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("USER_CREATE_TIME <=", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIn(List<Date> values) {
            addCriterion("USER_CREATE_TIME in", values, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotIn(List<Date> values) {
            addCriterion("USER_CREATE_TIME not in", values, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeBetween(Date value1, Date value2) {
            addCriterion("USER_CREATE_TIME between", value1, value2, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("USER_CREATE_TIME not between", value1, value2, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeIsNull() {
            addCriterion("USER_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeIsNotNull() {
            addCriterion("USER_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeEqualTo(Date value) {
            addCriterion("USER_UPDATE_TIME =", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeNotEqualTo(Date value) {
            addCriterion("USER_UPDATE_TIME <>", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeGreaterThan(Date value) {
            addCriterion("USER_UPDATE_TIME >", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_UPDATE_TIME >=", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeLessThan(Date value) {
            addCriterion("USER_UPDATE_TIME <", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("USER_UPDATE_TIME <=", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeIn(List<Date> values) {
            addCriterion("USER_UPDATE_TIME in", values, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeNotIn(List<Date> values) {
            addCriterion("USER_UPDATE_TIME not in", values, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("USER_UPDATE_TIME between", value1, value2, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("USER_UPDATE_TIME not between", value1, value2, "userUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Sun Mar 20 15:59:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}